### ISSUE TITLE
No output when --after-context is added

### ISSUE THREAD

**Issue by wezm** [BurntSushi/ripgrep#731] opened 2018-01-05 01:03 UTC
I'm grepping a log file as follows, which produces 313 matching lines:

```
rg 'WARN.*59082' log/server.log
```

When `--after-context` (or `-A`) is added no results are shown and `rg` exits with a status code of 1. It doesn't seem to matter what number is supplied to `--after context`.

```
rg --after-context=2 'WARN.*59082' log/server.log
```

A smaller log file I created to try to supply a test case works properly. The original log file is 742Mb. Performing the same operation (with `--after`) in `ag` yield results as expected.

Fresh debug and release builds from master (`14779ed`) yields the same result.

**OS:** Arch Linux (`4.14.10-1-ARCH #1 SMP PREEMPT Fri Dec 29 20:17:35 UTC 2017 x86_64 GNU/Linux`)
**ripgrep:** Installed via Arch package, version 0.7.1-1

```
$ rg --version
ripgrep 0.7.1
-AVX -SIMD
```

**Comment by BurntSushi** [comment] 2018-01-05 01:12
Thanks for reporting this! Unfortunately it is going to be hard to debug without a reproducible test case. Any chance you can try to wittle down your log file?

**Comment by wezm** [comment] 2018-01-05 01:17
I'm working on it. I have it down to 256Mb 🙂

**Comment by wezm** [comment] 2018-01-05 01:41
Ok I've found the source. There was a bunch of NUL bytes buried in the file. Not sure if this a case ripgrep should handle but reduced test case is attached.

[nul-bytes.log](https://github.com/BurntSushi/ripgrep/files/1605278/nul-bytes.log)

**Comment by okdana** [comment] 2018-01-05 02:32
It doesn't print your test case because it thinks the file is a binary. If you add `-a` it should work.

It is a bit hard to troubleshoot what it's doing when it just silently ignores it though. Maybe there should be a debug message?

Could be noisy if you have a lot of binaries in your repo or whatever, but that's what `ag` does:

```
DEBUG: File nul-bytes.log is binary. Skipping...
```

(At least, it does that with files on the file system — i don't think it can detect binary data on `stdin`.)

**Comment by wezm** [comment] 2018-01-05 02:42
Using `-a` does in fact fix it. I think some kind of message would have been super helpful. I figured there was a reason but there was nothing to go on to work out what it was. Extra confusion was caused by getting results without `-A` then adding it and getting none.

**Comment by BurntSushi** [comment] 2018-01-05 04:22
I suspect that #306 might be a duplicate then.

However, the presence or absence of `-A` shouldn't impact binary file detection... So that's worth looking into.

**Comment by BurntSushi** [comment] 2018-02-01 00:24
I can confirm that this is a dupe of #306. I couldn't see any problem with using `-A`.

**Closed by BurntSushi** 2018-02-01 00:24 UTC
