### ISSUE TITLE
Gitignore `{}` patterns are inconsistent with official git

### ISSUE THREAD

**Issue by quark-zju** [BurntSushi/ripgrep#1183] opened 2019-01-31 22:21 UTC
#### Versions

ignore crate: 0.4.6
git: 2.19.0

#### Problem

The `gitignore` man page does not mention that `{}` should be treated specially. The official git binary does not treat it specially. For example, `{a}` matches the literal `{a}`, not `a`.

The gitignore matcher in the `ignore` crate currently behaves differently.

Possible solution: Add an option in `globset` to disable `{}` handling. Make `gitignore` use it.

#### Reproduce code
 
```bash
git init foo; cd foo; echo '{a,b}' > .gitignore; touch a; touch '{a,b}'; git status
# prints "a" in "untracked files"; does not print "{a,b}"
```

```rust
use ignore::gitignore::GitignoreBuilder;
fn main() {
    let mut b = GitignoreBuilder::new(".");
    b.add_line(None, "{a,b}").unwrap();
    let m = b.build().unwrap();
    println!("'a' matched: {:?}", m.matched("a", false)); // Actual: Ignore; Expect: None
    println!("'{{a,b}}' matched: {:?}", m.matched("{a,b}", false)); // Actual: None; Expect: Ignored
}
```

**Comment by BurntSushi** [comment] 2019-04-03 13:10
This ticket is a duplicate of #1221, but since that one has more activity, I'm going to close this one. Thanks for filing the bug!

**Closed by BurntSushi** 2019-04-03 13:10 UTC
