### ISSUE TITLE
ripgrep doesn't use .gitignore by default

### ISSUE THREAD

**Issue by vpeopleonatank** [BurntSushi/ripgrep#1336] opened 2019-08-02 07:24 UTC
#### What version of ripgrep are you using?

Replace this text with the output of `rg --version`.
ripgrep 11.0.1 (rev 1f1cd9b467)
#### How did you install ripgrep?
via Ubuntu apt

#### What operating system are you using ripgrep on?
Pop!_OS 18.04 LTS x86_64

#### Describe your question, feature request, or bug.
ripgrep ignore my `.gitignore` but `.ignore` and `.rgignore` still works.

#### If this is a bug, what is the expected behavior?
ripgrep should you my .gitignore by default.

**Comment by BurntSushi** [comment] 2019-08-02 10:23
Please provide a reproduction by following the instructions in the issue template. For now, I'm closing this because it is unactionable.

**Closed by BurntSushi** 2019-08-02 10:23 UTC
