### ISSUE TITLE
rg on Windows keeps hanging

### ISSUE THREAD

**Issue by annazolkieve** [BurntSushi/ripgrep#2045] opened 2021-10-27 14:08 UTC
Jul 21 2020:
```
grep -r xxx .
xxx.c:extern void      xxx ( void )

ext code 0 / time elapsed 397ms

$ rg xxx
xxx.c
492: extern void      xxx ( void )

# rg hangs: have to interrupt rg via CTRL+C
exit code 127 / time elapsed 46m21s

rg version: ??
```

Oct 27 2021:
```
$ grep -r xxx .
./file1.cpp:     	xxx
./file2.cpp:     	xxx
...
./fileN.cpp:     	xxx
ext code 0 / time elapsed: 1.427s

$ rg xxx
./file1.cpp:     	xxx
./file2.cpp:     	xxx
...
# rg hangs: have to interrupt rg via CTRL+C
exit code 127 / time elapsed: 29m28s

$ rg --version
ripgrep 13.0.0 (rev af6b6c543b)
-SIMD -AVX (compiled)
+SIMD -AVX (runtime)
```
Cannot share the directory, sorry.
OS: Win10 64-bit.

**Comment by chuanqisun** [comment] 2021-11-11 01:24
Not sure if it's related. I'm maintaining an app that calls the `rg` command from node.js, using [child_process.exec](https://nodejs.org/api/child_process.html#child_processexeccommand-options-callback) api. [Here](https://github.com/osmoscraft/osmosnote/blob/master/packages/server/src/routes/search-note.ts#L126) is how the rg command is being generated, and [here](https://github.com/osmoscraft/osmosnote/blob/master/packages/server/src/lib/run-shell.ts) is how the `exec` is being called. After I upgrade from rg 12.1.1 to 13.0.0, the `exec` never calls the callback. Some more observations:
1. I was able to manually execute the same command in terminal without any problems.
2. The `exec` can execute other shell command like `ls` or `git` without any problems.

So, for what it's worth, I wonder if there were some changes in 13.0.0 that affected how the process exits, and because of that, node.js stop receiving the exit signal.

**Comment by BurntSushi** [comment] 2021-11-11 13:35
Closing this due to lack of reproduction.

**Comment by matkoniecz** [comment] 2021-11-22 14:28
> Closing this due to lack of reproduction.

It is still open

**Closed** 2021-11-22 14:51 UTC
Labels: invalid
