### ISSUE TITLE
Usage with vim/neovim and fzf.vim

### ISSUE THREAD

**Issue by CrashyBang** [BurntSushi/ripgrep#81] opened 2016-09-25 09:37 UTC
I am trying to set this up with [fzf.vim](https://github.com/junegunn/fzf.vim) and as per this [comment](https://github.com/junegunn/fzf.vim/pull/36#issuecomment-249406310) `rg` does not seem to currently work.

I was hoping you would have some insight into this?

Cheers.

**Comment by junegunn** [comment] 2016-09-25 10:39
Another problem I noticed is this:

<img width="341" alt="rg-column" src="https://cloud.githubusercontent.com/assets/700826/18814749/b520b9e4-8357-11e6-8d25-6c9a8da610ed.png">

I don't think it's intentional?

**Comment by mgee** [comment] 2016-09-25 11:13
You mean the missing line numbers? If the output is not to a tty the parameter for line numbers -n has to be explicitly specified.

**Comment by BurntSushi** [comment] 2016-09-25 12:49
Yes, it is intentional. When searching at a tty, line numbers, headings and colors are enabled by default. Otherwise, the default format is the same as `git grep`.

I otherwise don't know what the problem is here. Could you please describe it in more detail?

**Comment by junegunn** [comment] 2016-09-25 13:02
I see, so then it's not a problem. The issue we have is that the output of rg (0.1.17) is not captured by `system()` function of vim unlike grep or ag.

```vim
:echo system('ag foo')
:echo system('grep foo *')

:echo system('rg foo')
```

**Comment by BurntSushi** [comment] 2016-09-25 14:21
I think `rg` and `grep` actually have the same behavior here. If you pass a file path argument, then `stdin` is ignored. The issue here is what happens when no path is given. Here's an illustration:

```
$ echo PM_RESUME | ag PM_RESUME | wc -l
1
$ ag PM_RESUME < /dev/null | wc -l
16
$ echo PM_RESUME | rg PM_RESUME | wc -l
1
$ rg PM_RESUME < /dev/null | wc -l
0
```

I bet this is the same bug that's being seen in #35.

**Comment by BurntSushi** [comment] 2016-09-25 15:13
Hooray, this is indeed a dupe of #35! Fixing this fixes that too.

**Comment by BurntSushi** [comment] 2016-09-25 15:15
Weird. Github didn't close this. Fixed in ab0d1c1c797c0464ad4fcdfc641bcf88f9ade304.

**Closed by BurntSushi** 2016-09-25 15:15 UTC

**Comment by CrashyBang** [comment] 2016-09-25 20:26
So just to clarify does `rg` need to be invoked with `--column` or `--no-heading` for this to now work?

Going of #35..?

Cheers.

**Comment by BurntSushi** [comment] 2016-09-25 20:30
@CrashyBang I don't think the problem has actually been explained to me, but I imagine you'd want `rg --no-heading --vimgrep`.

**Comment by CrashyBang** [comment] 2016-09-25 20:49
Hey @BurntSushi okay sweet will go over as soon as I am home from work will let you know how it goes hoping to do a write up on medium `rg` has already massively supercharged my workflow.

**Comment by BurntSushi** [comment] 2016-09-25 20:56
@CrashyBang glad to hear it! Please send a link over if you do that write up. :-) (I'd also be happy to read a draft.)

**Comment by CrashyBang** [comment] 2016-09-26 06:17
Hey @BurntSushi write up here: https://medium.com/@crashybang/supercharge-vim-with-fzf-and-ripgrep-d4661fc853d2 sorry wanted to get it up but still making tweaks if needed.

**Comment by junegunn** [comment] 2016-09-26 06:46
@CrashyBang I would advise against suggesting `-i` and `-e` as the default. fzf by default performs smart-case matching which is really handy with CamelCase files. `-i` disables that and makes the search always case-insensitive. You might also want to experiment without `-e` especially because of [the new scoring mechanism](https://github.com/junegunn/fzf/issues/638) introduced in 0.15.0.

**Comment by CrashyBang** [comment] 2016-09-26 06:57
Hey @junegunn noted and removed :).
