### ISSUE TITLE
completion/fish: Options are not completed after the first non-option argument

### ISSUE THREAD

**Issue by zx8** [BurntSushi/ripgrep#1970] opened 2021-08-11 10:26 UTC
#### What version of ripgrep are you using?

v13.0.0

#### How did you install ripgrep?

Homebrew

#### What operating system are you using ripgrep on?

macOS

#### Describe your bug.

When using `fish`, completions cease to work after the first argument which doesn't start with a `-`

#### What are the steps to reproduce the behavior?

```sh
$ rg --<TAB>
# observe that options are completed

$ rg foo --<TAB>
# observe that options are NOT completed
```

#### What is the expected behavior?

Options after the first non-option argument should still be completed, since ripgrep accepts options in any order (except after an explicit `--` argument to signal the end of option arguments, of course)

**Comment by BurntSushi** [comment] 2021-08-11 11:45
Unfortunately I'm going to mark this as `wontfix`.

The problem here is that Fish auto-completions are auto-generated by ripgrep's arg parser, clap. The only manually maintained shell completions are for zsh, and it shows. They are excellent and the rest... not so much. In retrospect, I somewhat regret including auto-generated shell completions in the release, because I don't control them.

With respect to this particular issue, I'm going to close it, because I don't have any plan for working on it. However, I think there are two avenues for fixing this:

1. Write a simple Rust program that reproduces the issue and file it against the Clap arg parser project. And try to get it fixed there. ripgrep will automatically benefit the next time it upgrades to the latest release of Clap.
2. Get rid of the auto-generated completions and hand-maintain them. This is what we do for zsh. I am not particularly excited about this option, but if it has the same kind of infrastructure support as the zsh completions do (excellent docs _and_ testing), then I think I'd be willing to take it on.

**Closed by BurntSushi** 2021-08-11 11:45 UTC

**Comment by zx8** [comment] 2021-08-11 13:31
Aha... While trying to debug the cause of the issue, I found a PR that actually addresses it already (https://github.com/clap-rs/clap/pull/2359) but it seems ripgrep hasn't updated yet.

I'll just be patient. Thanks! 😉

**Comment by BurntSushi** [comment] 2021-08-11 13:34
Unfortunately, for the past few years, clap has been working on a v3. I don't actually even know whether that PR was merged into the v2 version or not. Either way, it doesn't matter, because there hasn't been a release of clap in almost a year: https://crates.io/crates/clap/versions --- So ripgrep can't update. The whole thing has been pretty confusing to me to be honest.

In any case, once clap 3 is out, I plan to migrate as long as there are no blocking issues discovered.

**Comment by zx8** [comment] 2021-08-11 13:55
Oh wow, I wasn't aware of the release cadence situation... and the whole v2 → v3 things sounds like the Python saga all over again. 😁 

I'll patch my local completions for now while waiting for Clap to get things sorted out on the release side of things.

Thanks a lot for all your hard work on `ripgrep` – my daily routine wouldn't be the same without it. 😍

**Comment by BurntSushi** [comment] 2021-08-11 14:03
No it's definitely nowhere near the Python saga in terms of scale or impact. :-) The v2/v3 thing itself isn't an issue. It's just that it has been in a state of limbo for a very long time. I have zero problems doing a migration with a bunch of breaking changes. That's easy. And I don't have to live with v2 and v3 compatibility in ripgrep simultaneously. The Python saga made both of those things (migration and compatibility) very very difficult.

And aye, good luck with the local patching!
