### ISSUE TITLE
Ability to link to home directory/other environment variables in config file.

### ISSUE THREAD

**Issue by alanxoc3** [BurntSushi/ripgrep#1812] opened 2021-03-02 19:10 UTC
I have a rg config file that looks like this:
```
...
--ignore-file=/home/<username>/.dotfiles/search-ignore
...
```

This works fine on my linux machine, but it breaks when I switch to my mac machine, because the username is different and the home directory is in `/Users/...`.

As far as I can tell, the config file doesn't interpret any environment variables or shell expansions. For example, neither of these work:
```
--ignore-file=$HOME/.dotfiles/search-ignore
--ignore-file=~/.dotfiles/search-ignore
```

In my usecase, it would be nice if there was a built-in way to get the home directory/expand environment variables. I understand if that's out of scope though and I can work around it.

**Comment by BurntSushi** [comment] 2021-03-02 20:06
Duplicate of #931, #1548, #1666 and #1792.

**Closed by BurntSushi** 2021-03-02 20:06 UTC
