### ISSUE TITLE
Multiline lookbehind, empty submatches array

### ISSUE THREAD

**Issue by roblourens** [BurntSushi/ripgrep#1412] opened 2019-10-28 04:50 UTC
If I search with a lookbehind pattern that matches a newline, and use the `--json` flag, I get the match info but it has an empty `submatches` array. Example:

```
$ echo -e 'foo\nbar' > test.txt
$ rg --auto-hybrid-regex --multiline --json '(?<=foo\n)bar' test.txt
{"type":"begin","data":{"path":{"text":"test.txt"}}}
{"type":"match","data":{"path":{"text":"test.txt"},"lines":{"text":"bar\n"},"line_number":2,"absolute_offset":4,"submatches":[]}}
{"type":"end","data":{"path":{"text":"test.txt"},"binary_offset":null,"stats":{"elapsed":{"secs":0,"nanos":40700,"human":"0.000041s"},"searches":1,"searches_with_match":1,"bytes_searched":8,"bytes_printed":183,"matched_lines":1,"matches":0}}}
{"data":{"elapsed_total":{"human":"0.002328s","nanos":2328499,"secs":0},"stats":{"bytes_printed":183,"bytes_searched":8,"elapsed":{"human":"0.000041s","nanos":40700,"secs":0},"matched_lines":1,"matches":0,"searches":1,"searches_with_match":1}},"type":"summary"}
```

Compare to what I get when matching with lookbehind on one line:

```
$ rg --auto-hybrid-regex --multiline --json '(?<=b)ar' test.txt 
...
{"type":"match","data":{"path":{"text":"test.txt"},"lines":{"text":"bar\n"},"line_number":2,"absolute_offset":4,"submatches":[{"match":{"text":"ar"},"start":1,"end":3}]}}
```

Or just matching that line 

```
$ rg --auto-hybrid-regex --multiline --json 'bar' test.txt
...
{"type":"match","data":{"path":{"text":"test.txt"},"lines":{"text":"bar\n"},"line_number":2,"absolute_offset":4,"submatches":[{"match":{"text":"bar"},"start":0,"end":3}]}}
```

Same with lookahead that matches a newline.

**Comment by alessandroasm** [comment] 2020-10-05 18:47
Hi, I looked into what is happening in this case.

https://github.com/BurntSushi/ripgrep/blob/def993bad1a9275cdc249f04048e5b2065b79f05/crates/printer/src/json.rs#L604-L614

The issue is that `grep_searcher::SinkMatch` doesn't store captured groups. When `JSONSink` needs details about capture groups, it reruns the matcher against the bytes in `SinkMatch`, but those bytes only contain the current line, which in turn results in a non-match scenario.

I think the way to go here will be including submatch data in `grep_searcher::SinkMatch`. That way we won't need to rerun the matcher to get this information.

@BurntSushi I can implement that if you agree to this changes

**Closed** 2021-06-01 01:51 UTC
Labels: bug, rollup
