### ISSUE TITLE
Autogenerated usage mismatches binary name

### ISSUE THREAD

**Issue by kpp** [BurntSushi/ripgrep#426] opened 2017-03-30 16:23 UTC
```
$ rg -h | head -n14 | tail -n 1
USAGE:ripgrep [OPTIONS] <pattern> [--] [path]...
```

It should be `USAGE:rg [OPTIONS] <pattern> [--] [path]...`

**Comment by BurntSushi** [comment] 2017-03-30 16:35
This is a dupe of #418 I think. That is, I think it's the same underlying regression.

I think this was supposed to be fixed in the latest version of clap, but it's not.

**Comment by kbknapp** [comment] 2017-03-30 17:09
Looking at it now ;-)

**Comment by kbknapp** [comment] 2017-03-30 17:20
I found the issue.

**Comment by kpp** [comment] 2017-03-30 19:10
Ah, I see. Thank you!

**Comment by BurntSushi** [comment] 2017-03-30 20:03
@kbknapp Wow! I'm surprised Github closed this issue from your PR. (I'm reopening it because it doesn't actually get fixed until deps are bumped... Hah.)

**Comment by BurntSushi** [comment] 2017-03-30 20:04
Probably because I once tried to set up @homu on this repo, and so it has access. Cool.

**Comment by kbknapp** [comment] 2017-03-30 20:06
Wow I had no idea that would happen, I apologize! I'd almost call that a bug, since I shouldn't be allowed to close your PRs and Issues 😜

**Closed** 2017-03-31 19:56 UTC
