### ISSUE TITLE
Different behaviour from grep/ag with -o and multiple matches

### ISSUE THREAD

**Issue by passcod** [BurntSushi/ripgrep#468] opened 2017-04-29 01:24 UTC
With grep:

```
$ echo '50k + 1k + 11k + 37k + 18k' | grep -Po '[\d.]+'
50
1
11
37
18
```

With The Silver Searcher:

```
$ echo '50k + 1k + 11k + 37k + 18k' | ag -o '[\d.]+'
50
1
11
37
18
```

With ripgrep:

```
$ echo '50k + 1k + 11k + 37k + 18k' | rg -o '[\d.]+'
50
50
50
50
50
```

```
$ rg -V
ripgrep 0.5.1
```

**Comment by BurntSushi** [comment] 2017-04-29 01:36
I think this is a dupe of #451, which is fixed on master.

**Closed** 2017-04-29 01:54 UTC
Labels: duplicate
