### ISSUE TITLE
Ripgrep has severe problems with special chars (in this case umlauts)

### ISSUE THREAD

**Issue by nickbe** [BurntSushi/ripgrep#1556] opened 2020-04-20 13:38 UTC
ripgrep 12.0.0 (rev b9cd95faf1)
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)

Binary release
Windows 10

Even when simply searching a string which is only in the same line as an umlaut,
rg does not match the result. For example: Text line is "Lünen" - I'm searching for "nen". Result comes back empty though. 

Actually ripgrep would have to be at least able to cope with lines that contains special characters like umlauts, if not being able to search for them.

**Comment by BurntSushi** [comment] 2020-04-20 13:46
Closing, because I cannot reproduce:

```
$ echo 'Lünen' | rg 'nen'
Lünen
```

Assuming you're experiencing an issue, please consider providing more details. When opening a new bug report, there should be a template with a set of questions for you to answer. It's there for a reason. I'm not sure why you ignored it.

**Closed by BurntSushi** 2020-04-20 13:46 UTC
