### ISSUE TITLE
Add a flag for snake case/camel case insensitivity 

### ISSUE THREAD

**Issue by KJSanchez** [BurntSushi/ripgrep#2877] opened 2024-08-23 15:14 UTC
I have a python backend that passes a stripe subscription field called `cancel_at_period_end` to the frontend. The frontend team prefers that our response objects use a camel case naming convention. My reluctance is that it'll add friction to code navigation because `rip grep cancel_at_period_end` will return one set of results and `rip grep cancelAtPeriodEnd` will return another. I always need to see these results together for an effective full stack debugging workflow.

One alternative would be to use `-E` -- I'd just need to programmatically build the pattern given a camelcase or snake case string. However I imagine there's enough full stack developers with this problem that it's worth adding to core.

**Comment by BurntSushi** [comment] 2024-08-23 15:18
Duplicate of #1371.

**Closed by BurntSushi** 2024-08-23 15:18 UTC
Labels: duplicate
