### ISSUE TITLE
Categorize options in --help and man page

### ISSUE THREAD

**Issue by dfabulich** [BurntSushi/ripgrep#1893] opened 2021-06-14 19:13 UTC
When you run `rg --help` or `man rg` it presents a giant list of 100 options in alphabetical order. Related options like `--heading` and `--no-heading` do not appear together.

By comparison, `man grep` (for GNU grep) presents its options in categories: https://linux.die.net/man/1/grep

* Generic Program Information (`--help`, `--version`)
* Matcher Selection (`--extended--regexp`, `--perl-regexp`)
* Matching Control (`--ignore-case`, `--invert-match`)
* General Output Control (`--files-with-matches`, `--count`, `--silent`)
* Output Line Prefix Control (`--line-number`, `--no-filename`)
* Context Line Control (`--after-context`, `--before-context`)
* File and Directory Selection (`--exclude`, `--include`)

Skimming through the options for ripgrep, I think a similar list of categories would work.

**Comment by BurntSushi** [comment] 2021-06-14 19:26
Dupe of #1814

**Closed by BurntSushi** 2021-06-14 19:26 UTC
Labels: duplicate
