### ISSUE TITLE
Is there an indexing option?

### ISSUE THREAD

**Issue by rjammala** [BurntSushi/ripgrep#874] opened 2018-04-02 21:36 UTC
Is there an indexing option? If not, is it worth adding that feature?

**Comment by BurntSushi** [comment] 2018-04-02 22:14
Dupe of #95

**Closed by BurntSushi** 2018-04-02 22:14 UTC

**Comment by BurntSushi** [comment] 2018-04-02 22:26
(@rjammala If you or anyone has specific questions, I'd be happy to answer them.)
