### ISSUE TITLE
System freeze 

### ISSUE THREAD

**Issue by wagnerand** [BurntSushi/ripgrep#975] opened 2018-07-10 12:42 UTC
#### What version of ripgrep are you using?

```
$ rg --version
ripgrep 0.8.1
-SIMD -AVX
```

#### How did you install ripgrep?

`brew install ripgrep`

#### What operating system are you using ripgrep on?

macOS 10.13.6

#### Describe your question, feature request, or bug.

I use `rg` to search on a USB 3.1 SDD drive connected to my Macbook Pro 15" (2017). The SSD contains over 700GB of data, mostly small code files and binaries, like pictures.

Pretty much any search I issue on this corpus makes the system unresponsive a few minutes after I started it. The system hangs last from a few seconds to several minutes and appear every few minutes, with seemingly increasing frequency over time.
Sometimes, I just see the mac-like *beachball*, sometimes I can still switch windows and scroll, but most interactions aren't executed right away, instead it seems they're put into some queue and then executed after the system is unblocked.

Example search: `rg -F files.com -i -uu`

**Comment by BurntSushi** [comment] 2018-07-10 13:06
At a high level, this kind of issue isn't something I can reproduce, so it's unlikely to get fixed without someone who _can_ reproduce it digging into this and debugging it on their own.

With that said, I have some tips that might help you debug it:

* Do you have your system's swap enabled? From the symptoms you describe, it _sounds_ like your system is churning through memory. That is, if ripgrep (or your system's page cache) is eating up all your memory and stealing it from other applications, then it's possible your application's memory use is spilling over to disk via swap. When you use those applications again, it needs to read memory back from disk, which can be quite slow!
* What kind of memory usage is ripgrep itself using? I don't use macOS, but you'll need to use whatever tooling there helps you discover this kind of information. `htop` is an easy way of doing this for long lived processes. Look at the `RES` column (short for "resident" memory). You should also note the `SHR` column as well, especially if it gets large. The `VIRT` column is likely uninteresting for this diagnosis.
* Is ripgrep just eating up all of your CPU? This is a banal explanation, but it's possible. Consider forcing ripgrep to only use a single thread with the `-j1` flag. You should also try this experiment if memory usage is a problem, since the memory usage profile for ripgrep is different between single threaded and multi-threaded mode.
* Another set of flags to try is `--no-mmap` and `--mmap`. Namely, try one search with `--no-mmap` and another with `--mmap`, and see how that impacts system performance along with memory usage. They should, in theory, have different memory usage profiles. Compare them with `-j1` and without `-j1` as well.

Also, you say that your SSD contains 700GB, but that this includes binary data like pictures. ripgrep should skip most of that.

**Comment by wagnerand** [comment] 2018-07-10 15:03
Thank for your prompt reply!

System swap is enabled, but that doesn't seem to be the issue. Swap remained small and stable for all cases where I could reproduce the system freeze. (about 350mb, which is fairly low).

RES memory also doesn't seem to be an issue. I saw it spiking up to 800mb, but usually it's much lower than that, 300-600mb. Neither `htop` nor Apple's *Activity Monitor* show SHR.

ripgrep is eating some CPU, but not all of it. I have a quad-core i7. All, load is distributed more or less evenly across the cores. What I found interesting is that, whenever the system freezes, *all* processes are going into *Paging* status (W) and the CPU usage drops, except for Core 0, which is at 100% capacity used solely by the `kernel_task` process.

Using `--no-mmap` was the only thing that seems to avoid the freeze. Maybe `-j1` too, but I need to parallelism because otherwise searches are taking forever.

Is `--no-mmap` significantly slower than `--mmap` for my use-case?

**Comment by wagnerand** [comment] 2018-07-10 15:08
Uhm, I guess I was too fast. I also freezes when using `--no-mmap`. Just took a little longer.

**Comment by BurntSushi** [comment] 2018-07-10 15:17
Thanks for the detailed response. Based on the information you've given, my best guess is that swap is indeed the problem, or that your system is somehow not dealing with the additional memory usage. You also haven't said how much RAM your machine actually has, which makes it a bit difficult to guess here. Moreover, the _amount_ of swap your system is using isn't really relevant here, what matters is that it's being used, and also, _what_ is using it. Just because only 350MB is being used doesn't mean that isn't where all of your applications' memory has been paged to. If an applications memory is put into swap, then the decrease in CPU usage and overall slugginess is a _classic_ symptom of that.

> Maybe -j1 too, but I need the parallelism because otherwise searches are taking forever.

I mean, you only have a quad core. At best, you're going to get a 4x speed up (maybe 5x with HT), so I wonder what the difference is between "taking forever" and "taking forever divided by 4." Moreover, we are trying to **debug** the issue here. Let's not mix trying to find the cause with possible solutions. Could you please try experimenting with `-j1` and the combinations of `--mmap` and `--no-mmap`?

> Is `--no-mmap` significantly slower than `--mmap` for my use-case?

When searching a directory, `--no-mmap` is the default. `--mmap` in theory shouldn't be significantly slower, but it depends.

**Comment by wagnerand** [comment] 2018-07-10 15:23
> You also haven't said how much RAM your machine actually has, which makes it a bit difficult to guess here.

Oops, I meant to add that. The system has 16G of RAM, during all testing, usage never exceeded 8G.

> If an applications memory is put into swap, then the decrease in CPU usage and overall slugginess is a classic symptom of that.

I know what you are saying but this is different. The system freezes entirely, at some point, the only thing that I can do is moving the mouse around. Applications that get swapped shouldn't freeze the entire system for minutes.

> Could you please try experimenting with -j1 and the combinations of --mmap and --no-mmap?

Please see my added comment. It looks like `--no-mmap` vs `--mmap` doesn't make much of a difference. I can retry with `-j1` though.

**Comment by wagnerand** [comment] 2018-07-10 15:30
Got it, thanks! I am happy to dig into this and debug myself, but I guess I would need some guidance for that.

**Comment by BurntSushi** [comment] 2018-07-10 15:37
I'm not sure there are any specific code changes that need to be made to ripgrep. The next step I would personally try if I were you would be to attempt to refine the swap hypothesis. The most obvious way to do that, IMO, is to disable swap and see what happens. If things work better, then we have pretty compelling evidence that it's swap. If things don't work better, then it's possible that swap isn't the problem, but I think it may be difficult to draw a strong conclusion. At least, I don't feel comfortable doing so because I'm not familiar with how macOS systems behave in those scenarios.

If things do work better without swap enabled, then the hypothesis there is that your application's memory would never get paged out and as a result, the size of your I/O cache would be more forcefully limited. The I/O cache size is unlikely to impact the performance of ripgrep in this case, since if you are indeed actually searching 700GB (although that isn't actually clear to me, since I don't know what ripgrep is skipping due to binary data detection), then the I/O cache size is unlikely to be a factor since ripgrep is going to be blocked on disk anyway.

**Comment by wagnerand** [comment] 2018-07-10 17:12
I disabled swapping, and tried with and without memory maps, without any luck. The system freezes shortly after starting rg.

**Comment by BurntSushi** [comment] 2018-07-10 17:18
Sadly, I'm out of ideas. I've tried reproducing this on a very large directory of media files (enabling binary search), and ripgrep behaves as expected: fairly low memory usage and low CPU usage because it's disk bound.

I doubt there is much more I can do without the ability to reproduce your problem. You're probably on your own.

Keep in mind that you have still left out important data:

* The impact of using `-j1`.
* The impact of similar tools such as `ag` and/or `ggrep`.

**Comment by cyrossignol** [comment] 2018-07-12 00:58
This really sounds like a hardware, kernel module (driver), or power/temperature management issue, possibly related to the specific SSD or its USB driver. I seems very unlikely that ripgrep causes the problem directly.

As suggested, invoking `rg` with `-j1` may help by limiting ripgrep to one core so it generates less heat or concurrent IO (I seem to remember an issue with Macs preemptively throttling all non-system processes under certain conditions to keep the temperature lower). 

Running `ag` with enough workers to exercise all the cores may help to support this theory if we see the same behavior.

**Comment by BurntSushi** [comment] 2018-07-22 13:10
I don't think there's anything actionable on my end here. In theory, there are more debugging steps that could be performed to diagnose this issue, but at this point, it's up to the OP.

**Closed by BurntSushi** 2018-07-22 13:10 UTC
Labels: question

**Comment by wagnerand** [comment] 2018-07-23 19:05
Sorry, work has kept me more than busy.

Running with `-j1` has similar effects, although much less impactful. The system hangs are usually less than a second.
I didn't have time to test with `ag` or `ggrep` yet.

Would you like me to keep updating this issue?

**Comment by BurntSushi** [comment] 2018-07-23 19:57
More data is appreciated. If there is anything actionable on my end, I can
reopen, but I do suspect this debugging task is largely on your hands.
