### ISSUE TITLE
Error parsing regex near 'E:\Relea' at character offset 3: Unrecognized escape sequence: '\R'.

### ISSUE THREAD

**Issue by jiangjianshan** [BurntSushi/ripgrep#338] opened 2017-01-22 04:26 UTC
Hello,

    I want to combine to use ripgrep and CtrlP together, but meet the following issue as the picure showing:
![image](https://cloud.githubusercontent.com/assets/20179047/22179973/7cdcb74c-e09d-11e6-993a-4ee130481917.png)

    As you see my setting for the plugin CtrlP. I think the issue is came from the below line
let g:ctrlp_user_command = 'rg %s --files --color=never --glob ""'
    The version of ripgrep I'm using is 0.4.0, which is installed from commad 'cargo install ripgrep'. 
    Is it something wrong for my setting for the rg command or any other reasong to cause this issue?

**Comment by BurntSushi** [comment] 2017-01-22 05:24
I think this is a dupe of #326.

**Comment by jiangjianshan** [comment] 2017-01-22 06:30
@BurntSushi, I have look through the #326 issue, it seems like it is still open.  Below is what I'm try on my Windows 7 SP1 64bit system.
![image](https://cloud.githubusercontent.com/assets/20179047/22180601/419c07ac-e0af-11e6-8965-1be19034d3d0.png)

    I have already following the instruction on your github website to build ripgrep.
![image](https://cloud.githubusercontent.com/assets/20179047/22180597/344633d4-e0af-11e6-99c3-1677968beccf.png)

**Comment by BurntSushi** [comment] 2017-01-22 14:16
It is indeed still open. But it still looks like a duplicate to me. :-)

**Comment by jiangjianshan** [comment] 2017-01-23 14:49
@BurntSushi , I have found a new strange behaviour for command "rg --files [path]"
![image](https://cloud.githubusercontent.com/assets/20179047/22208362/9256afe4-e1bd-11e6-954e-202bc9c855b1.png)
   As you see above, the command "rg --files .\doc" worked at the folder "E:\Releases\lua-5.3.3", but "rg --files .\gnu_regex" not work at folder "E:\Releases\ctags-5.8".
   The version of Rust I'm using is 1.14.0, which target is x86_64-pc-windows-msvc. 
   When I'm using the command "cargo install ripgrep", I have noticed that the version of regex to compile ripgrep is 0.2.1 but not the 0.2 on this github.
   I'm still finding the solution for the issue I meet.

**Comment by BurntSushi** [comment] 2017-01-23 14:52
The bug is that the file path appears to be interpreted as a regex. If that's true, then your error messages make sense: `\d` is a valid escape sequence while `\g` is not.

> When I'm using the command "cargo install ripgrep", I have noticed that the version of regex to compile ripgrep is 0.2.1 but not the 0.2 on this github.

ripgrep uses [regex 0.2.1](https://github.com/BurntSushi/ripgrep/blob/master/Cargo.toml#L41).

**Comment by jiangjianshan** [comment] 2017-01-24 02:14
@BurntSushi, so what you mean this bug maybe came from regex 0.2.1?

**Comment by BurntSushi** [comment] 2017-01-24 02:17
No. It's clearly a bug in ripgrep proper. For some reason, the file path is
being parsed as a regex, but it shouldn't be. I haven't had a chance to
investigate further.

**Comment by jiangjianshan** [comment] 2017-01-24 04:12
@BurntSushi , Thanks, I will use ag for this moment to make some of my job can go on. Then I will switch back to rg when the bug has been solved.

**Closed** 2017-02-18 17:53 UTC
Labels: duplicate
