### ISSUE TITLE
global ignore / ripgreprc shell parameter expansion

### ISSUE THREAD

**Issue by anuramat** [BurntSushi/ripgrep#2771] opened 2024-03-30 12:32 UTC
# Motivation:

There are certain files that I want to keep in the vcs but don't want to ever search over.

As far as I understand, my options for now are (ordered by attractiveness, descending):
- A bunch of lines of `--glob` options in `ripgreprc`, which doesn't let me e.g. reuse [fd](https://github.com/sharkdp/fd) ignore file and kinda bloats the file
- Keeping the full path of global `.ignore` file in my `ripgreprc`, which would break on a different machine
- Using `alias rg="rg --ignore-file=$XDG_CONFIG_HOME/ripgrep/ignore"`, which wouldn't properly work e.g. with [telescope.nvim](https://github.com/nvim-telescope/telescope.nvim)

# Requested feature description

**Allow shell parameter expansion in ripgreprc**

This way one could use something like `--ignore-file=$XDG_CONFIG_HOME/ignore` straight in the ripgreprc

Besides, there might be other uses for this (probably not)

**Comment by BurntSushi** [comment] 2024-03-30 13:27
Duplicate of #931.

As for your specific problem, you've missed at least a couple choices. The first being the repository-specific-but-not-tracked-in-vcs `.git/info/exclude`. ripgrep supports that. And there is also [`core.excludesfile` in `git`](https://stackoverflow.com/questions/7335420/global-git-ignore) that ripgrep supports too. That seems like it's probably what you want.

**Closed** 2024-03-30 13:31 UTC

**Comment by anuramat** [comment] 2024-03-30 14:05
This used to work for me, but now the overlap between the git-ignored and ripgrep-ignored files isn't 100% (set difference is non-empty both ways)

Would something like `$RIPGREP_IGNORE_PATH` be unacceptable too?
