### ISSUE TITLE
Ripgrep parsing files in gitignore

### ISSUE THREAD

**Issue by spapanik** [BurntSushi/ripgrep#2830] opened 2024-06-04 10:00 UTC
### Please tick this box to confirm you have reviewed the above.

- [X] I have a different issue.

### What version of ripgrep are you using?

ripgrep 14.1.0

### How did you install ripgrep?

pacman (arch linux)

### What operating system are you using ripgrep on?

arch linux

### Describe your bug.

ripgrep raises an error when the gitignore contains {{any string}}

### What are the steps to reproduce the behavior?

I am running ripgrep in a template directory (for cookiecutter) with a .gitignore that contains the following line:

/{{cookiecutter.project_name}}.yml

### What is the actual behavior?

user@localhost $ rg 'string to match'
rg: ./.gitignore: line 14: error parsing glob '/{{cookiecutter.project_name}}.yml': nested alternate groups are not allowed

### What is the expected behavior?

ripgrep should parse .gitignore the same way as git does

**Comment by BurntSushi** [comment] 2024-06-04 10:37
Duplicate of #1221

**Closed by BurntSushi** 2024-06-04 10:38 UTC
Labels: duplicate
