### ISSUE TITLE
--vimgrep doesn't print anything when a file is specified

### ISSUE THREAD

**Issue by elirnm** [BurntSushi/ripgrep#466] opened 2017-04-27 23:48 UTC
When a specific file is specified for a search, running rg with `--vimgrep` results in nothing being printed. The `--vimgrep` option works fine if a specific file isn't specified.

This is with rg 0.5.1

Specifying a specific file (doesn't work):
![capture](https://cloud.githubusercontent.com/assets/19817004/25508720/f79a5a8c-2b68-11e7-967b-556e2c320935.PNG)

Not specifying a specific file (works):
![capt2ure](https://cloud.githubusercontent.com/assets/19817004/25508756/225f2270-2b69-11e7-8b7b-7c11e2ffba1b.PNG)

**Comment by BurntSushi** [comment] 2017-04-28 11:04
I can't reproduce this problem:

```
[andrew@Serval ripgrep-466] echo Haunting > titles.txt
[andrew@Serval ripgrep-466] rg Haunting
titles.txt
1:Haunting
[andrew@Serval ripgrep-466] rg Haunting titles.txt
1:Haunting
[andrew@Serval ripgrep-466] rg --vimgrep Haunting titles.txt
1:1:Haunting
```

**Comment by kpp** [comment] 2017-04-30 12:27
I have reproduced this problem only on **Windows**. Linux is fine.

![rg](https://cloud.githubusercontent.com/assets/467709/25564322/846ce00e-2db9-11e7-9756-3eb376286185.png)

**Comment by kpp** [comment] 2017-04-30 12:41
Test it with code on `Windows`:

```
// See: https://github.com/BurntSushi/ripgrep/issues/466
#[test]
fn regression_466_vimgrep_fails_on_windows() {
    let wd = WorkDir::new("regression_466_vimgrep_fails_on_windows");
    let path = "titles.txt";
    wd.create(path, "Haunting\n");

    let mut cmd = wd.command();
    cmd.arg("--vimgrep").arg("Haunting").arg(path);
    let lines: String = wd.stdout(&mut cmd);

    let expected = "\
1:1:Haunting
";

    assert_eq!(lines, expected);
}
```

**Comment by Taverius** [comment] 2017-05-29 19:33
I was noticing this too.

Just to be quadruply sure, I tried all variants of `rg` v0.5.2 provided: x86/x64, gnu/msvc

So hey, at least its not a compiler issue?

**Comment by elirnm** [comment] 2017-06-02 10:45
I did some combination testing on the arguments that `--vimgrep` is a combination of, and the issue seems to lie with `--color`. When a file is specified to search, setting either `--color never` or `--color ansi` will cause nothing to be printed, while the same command with `--color always` or `--color auto` will print the matches.

Everything behaves as expected if a filepath isn't specified, even if that exact path is given as the value to a `-g` argument. (That is, `rg blah test.txt --color never` fails while `rg blah -g test.txt --color never` succeeds.

**Comment by andschwa** [comment] 2017-07-06 18:31
To add to this confusing conversation: using rg 0.5.2, I'm getting invisible output, here's a copy paste:

```
$ rg -tcmake group.cpp
src\CMakeLists.txt
471:  zookeeper/group.cpp
$ rg -tcmake group.cpp | echo
src\CMakeLists.txt:  zookeeper/group.cpp
```

And here's a screenshot:

![ripgrep](https://user-images.githubusercontent.com/2226434/27926796-858c71ca-623e-11e7-8ca6-93cfb4d4e4b8.PNG)

The result `src\CMakeLists.txt` is output, since it copied and pasted into here, but it's not rendering!

**Comment by elirnm** [comment] 2017-07-06 20:39
That is a colorization issue. See #403.

________________________________

**Comment by andschwa** [comment] 2017-07-06 21:34
@elirnm thank you a million! This has been aching me since I upgraded.

**Comment by BurntSushi** [comment] 2017-10-22 01:41
I'm not able to reproduce this on Windows in either cygwin or PowerShell. For others, is this bug still happening with the latest version of ripgrep?

**Comment by elirnm** [comment] 2017-10-25 01:55
No, this is working for me now with 0.7.1.

**Comment by kpp** [comment] 2017-10-28 17:18
This is working for me now with 0.7.1 under Windows & Linux. Would you please add my test from https://github.com/BurntSushi/ripgrep/issues/466#issuecomment-298229947 so we could catch the bug before releasing the code?

**Comment by BurntSushi** [comment] 2018-01-31 02:40
I can't reproduce this. Closing.

(I'd encourage folks that want to add tests to submit PRs. :-))

**Closed by BurntSushi** 2018-01-31 02:40 UTC
Labels: question

**Comment by kpp** [comment] 2018-01-31 22:41
I failed to write regression test. When I call rg from win console, there is no output `1:1:Haunting`, but when I run test, it passes:

```
...
test regression_428_unrecognized_style ... ok
test regression_466_vimgrep_fails_on_windows ... ok
test regression_451_only_matching ... ok
...
```

```
// See: https://github.com/BurntSushi/ripgrep/issues/466
#[test]
fn regression_466_vimgrep_fails_on_windows() {
    let wd = WorkDir::new("regression_466_vimgrep_fails_on_windows");
    let path = "titles.txt";
    wd.create(path, "Haunting\n");

    let mut cmd = wd.command();
    cmd.arg("--vimgrep").arg("Haunting").arg(path);
    let lines: String = wd.stdout(&mut cmd);

    let expected = "\
1:1:Haunting
";

    assert_eq!(lines, expected);
}
```
