### ISSUE TITLE
Support for `--and`, `--or`, `--not`, and grouped expressions a la Git Grep

### ISSUE THREAD

**Issue by zachriggle** [BurntSushi/ripgrep#1473] opened 2020-01-28 00:13 UTC
#### What version of ripgrep are you using?

ripgrep 11.0.2
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)

#### How did you install ripgrep?

`brew install ripgrep --HEAD`

#### What operating system are you using ripgrep on?

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.3
```

#### Describe your question, feature request, or bug.

I currently have a script pipeline that outperforms both vanilla `rg` and `git grep` while combining the latter's support for grouped boolean operators.

It would be useful if RipGrep supported these operators natively, so that composition of expressions could be more powerful.  Consider:

```
rg -e malloc --and --not '(' -e sizeof -e '\b1\b' ')'
```

The functionality supported by `git grep` is documented in the man pages, but the relevant excerpt has been reproduced below:

```
                  [--and|--or|--not|(|)|-e <pattern>...]
...
       -e
           The next parameter is the pattern. This option has to be used for
           patterns starting with - and should be used in scripts passing user
           input to grep. Multiple patterns are combined by or.

       --and, --or, --not, ( ... )
           Specify how multiple patterns are combined using Boolean
           expressions.  --or is the default operator.  --and has higher
           precedence than --or.  -e has to be used for all patterns.
```

Edit: Missing quotes

**Comment by BurntSushi** [comment] 2020-01-28 00:17
Duplicate of #875

**Closed by BurntSushi** 2020-01-28 00:17 UTC
Labels: duplicate

**Comment by zachriggle** [comment] 2020-01-28 00:24
Whoops, I should have searched first.  Thanks for the quick response and the awesome tool!
