### ISSUE TITLE
Handling of .gitignore files with escaped spaces is inconsistent with git

### ISSUE THREAD

**Issue by sedm0784** [BurntSushi/ripgrep#659] opened 2017-10-30 17:09 UTC
In short, git treats paths with escaped spaces in the same way as paths with spaces. ripgrep doesn't.

## Steps to reproduce:

1. `mkdir test_ignore`
2. `cd test_ignore`
3. `git init`
4. `echo "hi there" > "ignore me"`
5. `echo "ignore\\ me" >> .gitignore`
6. `git status` Note that the "ignore me" file is not listed.
7. `rg hi`

Observed results:

    ignore me
    1:hi there

Expected results:

There should be no output, because ripgrep should be ignoring the "ignore me" file.

I've just fixed my repo not to include the unnecessary escaping, so as far as I'm concerned this is pretty low priority ;).

**Comment by sedm0784** [comment] 2017-10-30 17:10
I've just fixed my repo not to include the unnecessary escaping, so as far as I'm concerned this is pretty low priority ;).

**Comment by okdana** [comment] 2017-10-30 17:15
Relevant: #526

I had a fix for this that seems to work fine on UNIX, but there are unresolved implications for Windows because `rg` supports `\` as a directory separator on that platform

**Comment by BurntSushi** [comment] 2017-10-30 17:33
Should we mark this as a duplicate of #526? I guess the user facing issue isn't quite the same, but I think they share the same resolution, right?

**Comment by okdana** [comment] 2017-10-30 17:34
Seems right, yeah

**Closed** 2017-10-30 17:35 UTC
Labels: duplicate

**Comment by sedm0784** [comment] 2017-10-31 10:16
Yep, sorry. I didn't spot that one when I skimmed the existing issues.
