### ISSUE TITLE
Option to show matches in filenames

### ISSUE THREAD

**Issue by Nudin** [BurntSushi/ripgrep#1901] opened 2021-06-17 12:32 UTC
I use ripgrep to browse source code, especially code that I'm not familiar with yet. A pattern I do very regullary when I want to know where some symbol (variable, function, class, script, whatever) is used is:
```
$ fd symbolname
$ rg symbolname
```
It would be nice to have this merged into one command as well as recive a single consistent output. I would therefore love to se an rg option `--search-filename` that will not only search the filecontents for matches of the supplied regexp but also the filenames. If a filename matches the regex but no line in it, the file would still be shown. If the filename matches and the file contains matching lines, filename and lines would be displayed as usual, except that the match in the filename would also be highlighted (if colors are enabled).

Simple example of how this could look like:
```
$ rg --search-filename symbolname
some-file.sh
5: Do something with symbolname
23: # call symbolname.sh
24: ./symbolname.sh

symbolname.sh

other-file-with-symbolname.sh
17: this is another file with symbolname
54: more occurences of symbolname
```

**Comment by BurntSushi** [comment] 2021-06-17 12:36
Dupe of #1034

**Closed by BurntSushi** 2021-06-17 12:36 UTC
