### ISSUE TITLE
.gitignore entry ignored depending on path parameter

### ISSUE THREAD

**Issue by mgee** [BurntSushi/ripgrep#49] opened 2016-09-24 04:35 UTC
Depending on the path parameter supplied to ripgrep on the commandline .gitignore patterns are ignored.

Setup:
```shell
$ mkdir -p test/foo/bar
$ touch test/foo/bar/baz
$ echo 'foo/bar' > test/.gitignore
```

When run with `test` as path parameter the `bar` directory is not ignored.
```shell
$ rg --debug --files "" test
DEBUG:grep::search: regex ast:
Empty
DEBUG:rg::ignore: test/.gitignore ignored because it is hidden
test/foo/bar/baz
```

When run inside test it is correctly ignored:
```shell
$ cd test
$ rg --debug --files ""
DEBUG:grep::search: regex ast:
Empty
DEBUG:rg::ignore: ./.gitignore ignored because it is hidden
DEBUG:rg::ignore: ./foo/bar ignored by Pattern { from: "./.gitignore", original: "foo/bar", pat: "foo/bar", whitelist: false, only_dir: false }
```

**Comment by BurntSushi** [comment] 2016-09-24 04:47
I think this is a dupe of #25. I'll be sure to include your setup as a regression test.

**Comment by BurntSushi** [comment] 2016-09-24 20:26
Actually, this is a dupe of #16. Fix incoming.

**Closed by BurntSushi** 2016-09-24 20:26 UTC
Labels: bug
