### ISSUE TITLE
Please provide a Debian/Ubuntu package

### ISSUE THREAD

**Issue by Naereen** [BurntSushi/ripgrep#280] opened 2016-12-12 11:18 UTC
It's surprising to see that ripgrep is available in almost all Linux distributions but not one of the most popular, Debian or Ubuntu (including {X,L,K,Ed}Ubuntu).

Could you try to provide a Debian/Ubuntu package, with a PPA (on launchpad)

**Comment by BurntSushi** [comment] 2016-12-12 11:29
> It's surprising to see that ripgrep is available in almost all Linux distributions but not one of the most popular

It shouldn't be surprising. People that aren't me need to put in the work to do it and we should all be grateful to those folks that ripgrep is in as many repositories as it is now.

Otherwise, this is a dupe of #10 

FWIW, there is ongoing effort to get Rust and ripgrep into the Debian repositories.

**Closed by BurntSushi** 2016-12-12 11:29 UTC

**Comment by Naereen** [comment] 2016-12-12 11:35
OK, sorry for the duplicate.

Thanks for your efforts (and for ripgrep itself!).
