### ISSUE TITLE
Add -z, --null-data param

### ISSUE THREAD

**Issue by kenorb** [BurntSushi/ripgrep#883] opened 2018-04-14 23:59 UTC
#### What version of ripgrep are you using?

`ripgrep 0.8.1`

#### What operating system are you using ripgrep on?

macOS High Sierra

#### Describe your feature request

GNU `grep` has the following option `-z`/`--null-data` to treat input and output data as sequences of lines, each terminated by a zero byte. This is especially useful when looking for patterns across multiple lines (read complete file into a single string).

- [Example 1](https://stackoverflow.com/a/152755/55075): `grep -Pzo '_name.*\n.*_description'
`
- [Example 2](https://stackoverflow.com/a/49763153/55075): `grep -qzP '(?s)(?=.*\bstring1\b)(?=.*\bstring2\b)(?=.*\bstring3\b)' file`

**Comment by BurntSushi** [comment] 2018-04-15 00:50
Dupe of #176.

**Closed by BurntSushi** 2018-04-15 00:50 UTC
