### ISSUE TITLE
Filenames invisible in PowerShell

### ISSUE THREAD

**Issue by mcandre** [BurntSushi/ripgrep#535] opened 2017-06-30 17:50 UTC
The default ripgrep color scheme renders well in Command Prompt and Git Bash, but filenames are perfectly invisible against the PowerShell default background color. Could we improve the ripgrep color scheme to play well with PowerShell?

As a workaround, I'm explicitly calling rg with `--color never` for now :/

**Comment by elirnm** [comment] 2017-06-30 18:18
See https://github.com/BurntSushi/ripgrep/issues/342. The root cause appears to be a bug in the Powershell host. A workaround is `--colors "path:style:intense"`.

**Comment by BurntSushi** [comment] 2017-06-30 19:15
This has been reported a couple of times and appears to be a dupe of #342.

> Could we improve the ripgrep color scheme to play well with PowerShell?

Anyone is welcome to propose a solution.

**Closed by BurntSushi** 2017-06-30 19:15 UTC
