### ISSUE TITLE
How to **whitelist** specific file extensions for listing with '--files'

### ISSUE THREAD

**Issue by n00bmind** [BurntSushi/ripgrep#333] opened 2017-01-18 13:52 UTC
Hi.
I'm using ripgrep primarily inside vim/ctrlp.
I'm currently working on a very big repository (tens of thousands of files) with a, let's say "relaxed" policy about what should be in version control and what should not, meaning I have to filter out a lot of binaries, build byproducts and whatnot.
I'm of course using a .ignore file at the root, which helps with speeding up the listings, but I need an additional layer of filtering to weed out so much "noise", so I'm trying to find an adequate syntax to use for the 'ctrlp_user_command' variable in vim which would _whitelist_ just what I'm interested in (only certain types of source files).
So far, I've obtained the best results by using the 'type-add' switch using the curly braces notation to include several file extensions, like this:
`rg . --files --type-add "source:*.{h,cs,c}" -tsource`

This _almost_ works, I can see most of the files listed have the extensions I specified, but there's also many unwanted files, like these two for instance:
`tools\webscarab\src\org\owasp\webscarab\plugin\scripted\script.bsh`
`tools\win32\python27\Lib\site-packages\data\themes\tools\icons48.code.tga`

For the first one I have no explanation. The second one would seem as if the '.code' part at the end was matching my '.c'.. Wild speculation, of course.

Any ideas?

**Comment by BurntSushi** [comment] 2017-01-18 14:07
What happens if you try:

```
rg . --files --type-add "source:*.{h,cs,c}" -tsource --debug
```

and

```
$ rg . --files -g '*.{h,cs,c}' --debug
```

**Comment by BurntSushi** [comment] 2017-01-18 14:07
Note that the `--debug` flag might cause a lot of output to `stderr`. If you can stick that in a gist or a pastebin, that would be great.

**Comment by chopsueysensei** [comment] 2017-01-18 18:11
I don't feel too comfortable sharing details about this particular project, so I'll try to find a suitable example and provide the info you requested..

**Comment by chopsueysensei** [comment] 2017-01-18 18:35
Ok, I'm using the Android SDK for this..
https://gist.github.com/chopsueysensei/bd0d7908f8d1b628cbb47b33a9b551b5

(I hope you can see all of it, it's pretty long)
I can see that it whitelists several thinks like images, jars and other things.
I'd say that paths that include a '.' somewhere are causing some trouble..

**Comment by BurntSushi** [comment] 2017-02-18 19:18
@chopsueysensei Could you please include the command you ran? Could you also tell me how to clone the repo you're searching?

**Comment by BurntSushi** [comment] 2017-02-18 19:19
I need enough information to reproduce the problem.

**Comment by chopsueysensei** [comment] 2017-02-22 15:34
The commands are the ones you asked me to run.
'rg_g_debug.txt' contains all the output from the command 'rg . --files -g '*.{h,cs,c}' --debug', while 'rg_t_debug.txt' contains all the output from 'rg . --files --type-add "source:*.{h,cs,c}" -tsource --debug'.

The tree is just my current Android SDK folder.

**Comment by BurntSushi** [comment] 2017-02-22 15:39
> The tree is just my current Android SDK folder.

Could you please tell me how to get it?

**Comment by chopsueysensei** [comment] 2017-02-22 15:41
Just install Android SDK anywhere in your HD.. maybe also open "SDK Manager.exe" located in the root folder and download a couple platform versions / optional components to add some more content to it..

**Comment by BurntSushi** [comment] 2017-02-22 15:45
@chocolateboy I'm not on Windows. I've never used the Android SDK before. Can you please link me to some instructions on how to acquire it? *I need to be able to reproduce your problem*.

**Comment by chopsueysensei** [comment] 2017-02-22 15:53
https://developer.android.com/studio/index.html#downloads

However, if you're not on windows, you probably won't get the same output right?

**Comment by chopsueysensei** [comment] 2017-02-22 15:54
Download the one under 'get just the command line tools'.
It should be a matter of unzipping then running.

**Comment by cheater** [comment] 2018-01-26 19:40
The android sdk is a red herring. You should be able to just create a file called foo.code.tga which is eg an ascii file with C inside it (for example) and it should be able to instruct rg to not find it.

**Comment by cheater** [comment] 2018-01-26 19:42
(by C i mean C source of course)

imo the perfect resolution would be to add something like gnu find syntax for specifying file names. At least -path, -name, -ipath, and -iname as well as -not, -o, -a, -\(, and -\).

Or at least -ipath and -iname for starters.

**Comment by okdana** [comment] 2018-01-26 19:56
* `rg`'s `--glob` and `--iglob` are effectively the same thing as `find`'s `-name`/`-path` and `-iname`/`-ipath` (though the semantics\* are slightly different obviously)
* `!`-prefixed patterns are effectively the same thing as `-not`
* as in `find`, multiple glob patterns are combined with an implicit `-a` by default

\* The pattern functionality is mostly as described here: https://git-scm.com/docs/gitignore

**Comment by cheater** [comment] 2018-01-26 19:58
Then I guess the issue can be closed as resolved? With the caveat that the original reporter should be able to reopen it if they are unhappy with the features rg provides.

**Comment by n00bmind** [comment] 2018-01-28 11:34
Is --glob the same as -g?
In that case, I already tried that as commented in my original post, and it still had some issues. It almost worked, but some files gave false positives..
My intention when opening this was more in the direction of bug catching & fixing.. I since have not used vim again in large codebases, so cannot attest as to how rg behaves currently in that scenario.

**Comment by BurntSushi** [comment] 2018-01-31 02:04
I am going to close this because it's not reproducible. If someone can come up with a contained example that uses something more accessible than the entire Android code base, then I can take a look and re-open this.

**Closed by BurntSushi** 2018-01-31 02:04 UTC
Labels: question

**Comment by alper** [comment] 2020-11-12 12:48
Thte manpage says:

    Only search files matching TYPE.

That does not help me to figure out what TYPE can be. I figured out in my case I have to say `-tgo` but that's fairly counterintuitive.

**Comment by BurntSushi** [comment] 2020-11-12 12:50
@alper How is `-tgo` counter intuitive? Please consider reading the [guide's section on filtering with file types](https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#manual-filtering-file-types).

**Comment by alper** [comment] 2020-11-12 12:55
Oh cool. The guide has examples so that makes it a lot easier. The man page does not.

Values concatenated onto the flag is not something I see a lot? I would expect: `-t go` but that could be just me.

**Comment by BurntSushi** [comment] 2020-11-12 13:08
> Values concatenated onto the flag is not something I see a lot? I would expect: `-t go` but that could be just me.

It's standard and idiomatic in UNIX command line since... forever. I don't know precisely when the convention started, but it is [specified by POSIX](https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html), which likely suggests the convention pre-dated POSIX. So it's probably been around for at least 32 years.

And `-t go` works as well.

**Comment by BurntSushi** [comment] 2024-03-26 16:49
That's not really what the usage is for. The usage is show the forms of allowable commands, not just prominent flags. Notice how the second form indicates that the only positional arguments are file paths, where as the first form indicates that the first positional argument is a pattern.

**Comment by disconnect3d** [comment] 2024-03-26 16:54
Yet, the usage/help fails to immediately show/explain to the user how to filter by filepaths/extensions.

I am pretty sure that many many people had the same issue and were annoyed that the usage doesn't show/explain `-g` or `-t`, but oh well.

**Comment by BurntSushi** [comment] 2024-03-26 17:02
> I am pretty sure that many many people had the same issue and were annoyed that the usage doesn't show/explain `-g` or `-t`, but oh well.

There are a _ton_ of things it doesn't show.

The `--help` page is very long, and if you start prioritizing things to fix issues like, then you end up with the opposite problem: things that really do need to be prioritized end up getting de-prioritized. Therefore, your suggestion is not _just_ "please prioritize this important feature," but it's _also_ "please also de-prioritize this other thing at the same time." In other words, a balance must be struct.

The user guide has several prominent sections on filtering. I think that's probably good enough IMO.

**Comment by cheater** [comment] 2024-03-26 17:52
As long as I can google for "ripgrep use type option" and there's something
exactly about what I need in the first 3 hits, I'm fine. Currently nothing
on the front page seems to be relevant. Obvious caveats about search
bubbles notwithstanding.

**Comment by cheater** [comment] 2024-03-26 18:45
it's the #1 result for me too. the search result snippet doesn't talk about
it. note i said "seems to be relevant"

**Comment by cheater** [comment] 2024-03-26 18:45
not just for that reason alone i'd suggest splitting that massive document
up into smaller ones

**Comment by BurntSushi** [comment] 2024-03-26 18:53
OK, well I don't control what snippet the search engine shows you.

I'm not splitting the guide into arbitrarily small pieces just so search engine results snippets are better.

The size of the document is large, which is why there is a table of contents.

**Comment by cheater** [comment] 2024-03-26 18:55
It's not just that. Long documents are overwhelming to people, especially
ones with reading and focus disabilities, which means most people nowadays.
It's really worthwhile to split this up into small pieces that just talk
about one thing. For most of the things talked about in this document there
isn't a really good reason to have them all in a single document.

**Comment by BurntSushi** [comment] 2024-03-26 19:07
I think we'll have to agree to disagree.
