### ISSUE TITLE
Expand variables in ripgrep.rc

### ISSUE THREAD

**Issue by rpdelaney** [BurntSushi/ripgrep#1666] opened 2020-08-26 18:46 UTC
#### Describe your feature request

In bash, I can invoke ripgrep with a custom ignores file like so:

```console
rg --ignore-file "$XDG_CONFIG_HOME/ripgrep.ignore"
```

However, the analogous setting in the ripgrep config does not resolve the path, as variable substitutions are interpreted literally. Only absolute paths allow ripgrep to succeed in finding the file:

```dosini
--ignore-file=$XDG_CONFIG_HOME/ripgrep.ignore     # bad
--ignore-file=~/.config/ripgrep.ignore            # bad
--ignore-file=/home/ryan/.config/ripgrep.ignore   # good
```

Being able to dynamically set configuration options in the rg config would enable me to use the same  config file on different platforms where configuration files are found in different places, as with macOS for example. This tempts me to alias `rg` to `rg --ignore-file...`, which feels like an anti-pattern when a configuration file is available.

**Comment by BurntSushi** [comment] 2020-08-26 19:06
Duplicate of #931 and #1548.

**Closed by BurntSushi** 2020-08-26 19:06 UTC
