### ISSUE TITLE
**.c

### ISSUE THREAD

**Issue by kngwyu** [BurntSushi/ripgrep#859] opened 2018-03-14 08:28 UTC
#### What version of ripgrep are you using?
ripgrep 0.8.1
-SIMD -AVX
#### What operating system are you using ripgrep on?
Arch Linux
#### Describe your question, feature request, or bug.

ripgrep's globset regards `**.c` as invalid.
Is it intended or bug ?

#### If this is a bug, what are the steps to reproduce the behavior?

``` bash
git clone https://github.com/rust-lang-nursery/rust-bindgen.git
cd rust-bidgen
rg aaaaaa
```

#### If this is a bug, what is the actual behavior?

```
rust-bindgen ) rg aaaaaa
./.gitignore: line 19: error parsing glob '**.orig': invalid use of **; must be one path component
```

**Comment by BurntSushi** [comment] 2018-03-14 18:00
This is a duplicate of #373. I am occasionally tempted to re-open it.

**Closed by BurntSushi** 2018-03-14 18:00 UTC
