### ISSUE TITLE
Don't match lines that start with a comment

### ISSUE THREAD

**Issue by flip111** [BurntSushi/ripgrep#712] opened 2017-12-11 18:49 UTC
How do i match a word `foo` that doesn't start with a comment `^\s*--`?

So this should match:
```
barfoo -- qux
    foo
foo bar
```

This should not match:
```
-- foo
     --
     -- foo
-- bar foo
```

**Comment by okdana** [comment] 2017-12-11 20:38
There's not really a great way to do it. You have to either build up a pattern with alternations enumerating the possible non-comment matches or pipe one `rg` into another.

If multiple `-e` patterns could be `AND`ed together rather than `OR`ed that would be a solution for you. Unfortunately, `rg` doesn't have that feature (yet) — see #473.

**Comment by BurntSushi** [comment] 2017-12-11 20:49
Yeah this is a duplicate of #473. Otherwise, `rg -v '^\s*--' | rg foo` works for now at the cost of losing the normal "pretty" format emitted by ripgrep.

**Closed by BurntSushi** 2017-12-11 20:49 UTC
