### ISSUE TITLE
Ability to write the replacements

### ISSUE THREAD

**Issue by ticki** [BurntSushi/ripgrep#179] opened 2016-10-14 17:10 UTC
`--replace` should have a way to write the replacements back to the disk. This allows for using `rg` as a `sed` replacement.

**Comment by kaushalmodi** [comment] 2016-10-14 17:22
This? (https://github.com/BurntSushi/ripgrep/issues/74)

**Comment by BurntSushi** [comment] 2016-10-14 17:39
Dupe of #74.

**Closed by BurntSushi** 2016-10-14 17:39 UTC
