### ISSUE TITLE
support for pager invocation

### ISSUE THREAD

**Issue by cehteh** [BurntSushi/ripgrep#1695] opened 2020-10-01 14:14 UTC
#### Describe your feature request

I use a wrapper around ripgrep to feed the output into 'less'.

```
cat /usr/local/bin/rgp
#!/bin/bash
rg -p "$@" | less -SR
```

Asking around, other people do so as well.

It would be nice if such a feature could be somehow integrated into rg itself. Either by a $PAGER env var or by a --pager option. Or chosen automatically when stdout 'isatty()' and a suitable pager is found.

**Comment by BurntSushi** [comment] 2020-10-01 14:22
Dupe of #86

**Closed by BurntSushi** 2020-10-01 14:22 UTC
