### ISSUE TITLE
Page output of rg,

### ISSUE THREAD

**Issue by sumonto** [BurntSushi/ripgrep#181] opened 2016-10-14 21:16 UTC
Hi,
Wondering if it is possible to add an option to page the output of rg instead of me having to do 
rg <string> --color always | less -r

Thanks.

**Comment by BurntSushi** [comment] 2016-10-14 21:32
Dupe of #86.

Specifically, try putting this in your `$HOME/bin`:

```
#!/bin/sh

/path/to/rg -p "$@" | less -RFX
```

**Closed by BurntSushi** 2016-10-14 21:32 UTC
