### ISSUE TITLE
Identify which patterns matched per line when using multiple patterns

### ISSUE THREAD

**Issue by prashanthellina** [BurntSushi/ripgrep#1453] opened 2020-01-03 15:57 UTC
#### What version of ripgrep are you using?

```
ripgrep 0.10.0
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)
```

#### How did you install ripgrep?

If you installed ripgrep with snap and are getting strange file permission or
file not found errors, then please do not file a bug. Instead, use one of the
Github binary releases.

#### What operating system are you using ripgrep on?

```
Distributor ID: Ubuntu
Description:    Ubuntu 19.10
Release:        19.10
Codename:       eoan
```

#### Describe your question, feature request, or bug.

When I do this,

```bash
rg -e "apple" -e "orange" myfile.text
```

The output has lines which match at least one pattern. It will be nice to have a feature where the output identifies which patterns matched.

**Comment by BurntSushi** [comment] 2020-01-03 16:00
Duplicate of #1286. Sorry.

**Closed by BurntSushi** 2020-01-03 16:00 UTC
Labels: duplicate

**Comment by TheTechromancer** [comment] 2024-05-22 15:12
@prashanthellina did you end up finding a solution to your problem of correlating regex patterns to their matches? I have a similar need. Thanks!
