### ISSUE TITLE
Feature Request: -AM: after context until matching braces found

### ISSUE THREAD

**Issue by stepancheg** [BurntSushi/ripgrep#1035] opened 2018-09-02 21:54 UTC
rg 0.9.0

`rg` has an option to display a specified number of lines after the match, e. g. `rg -A3`.

Often I use `rg` to find and print a function/macro/class/block etc.

`rg -AM` could work like `-A3` except instead of printing 3 line, it could print the block.

E. g. if the file is

```
mod foo;

fn bar() {
  if baz {
    qux();
  }
}

fn quux() {}
```

```
# rg -AM bar
fn bar() {
  if baz {
    qux();
  }
}
```

**Comment by BurntSushi** [comment] 2018-09-03 00:56
This is a duplicate of #502.

I remain undecided on whether or not to include this in ripgrep. It sounds like a maintenance mine field that I don't want to deal with.

**Closed by BurntSushi** 2018-09-03 00:56 UTC
Labels: duplicate
