### ISSUE TITLE
Feature Request: add -i option for "in place" find and replace

### ISSUE THREAD

**Issue by ElectricRCAircraftGuy** [BurntSushi/ripgrep#2115] opened 2022-01-02 06:32 UTC
#### Describe your feature request

Please add a `-i` / `--in-place` option (like in `sed`) to edit files in place. I'd really like to use ripgrep for find and replace across code bases, since it's so fast, but currently it requires some pretty difficult work-arounds to accomplish the desired behavior. 

Ex: for a single file I do this to replace all instances of `blue` with `red` in file `ip.txt`:
```bash
file_contents_and_stats="$(rg --stats --passthru 'blue' -r 'red' ip.txt)"
NUM_STATS_LINES=9
file_contents="$(head -n -$NUM_STATS_LINES "$file_contents_and_stats")"
stats="$(tail -n $NUM_STATS_LINES "$file_contents_and_stats")"
printf "%s" "$file_contents" > ip.txt
printf "%s" "$stats"
```

...but when trying to find across many files, this becomes much much harder, and I must first obtain a file list with `rg -l` then operate on that.

**Comment by BurntSushi** [comment] 2022-01-02 06:56
Dupe of #74.

**Closed by BurntSushi** 2022-01-02 06:56 UTC

**Comment by ElectricRCAircraftGuy** [comment] 2022-01-04 07:28
It was nontrivial, but I just wrote a wrapper around RipGrep to give it this feature. I call it `rgr` for RipGrep Replace, since it will do the find-and-replace feature on your disk. See installation instructions at the top of the file here: https://github.com/ElectricRCAircraftGuy/eRCaGuy_dotfiles/blob/master/useful_scripts/rg_replace.sh

Example usage from `rgr -h`:

```
EXAMPLE USAGES:

    rgr foo -r boo
        Do a *dry run* to replace all instances of 'foo' with 'boo' in this folder and down.
    rgr foo -R boo
        ACTUALLY REPLACE ON YOUR DISK all instances of 'foo' with 'boo' in this folder and down.
    rgr foo -R boo file1.c file2.c file3.c
        Same as above, but only in these 3 files.
    rgr foo -R boo -g '*.txt'
        Use a glob filter to replace on your disk all instances of 'foo' with 'boo' in .txt files
        ONLY, inside this folder and down. Learn more about RipGrep's glob feature here:
        https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#manual-filtering-globs
    rgr foo -R boo --stats
        Replace on your disk all instances of 'foo' with 'boo', showing detailed statistics.
```
