### ISSUE TITLE
[feature request]how about support rg -e foo|rg -v -e bar in one command

### ISSUE THREAD

**Issue by jixiuf** [BurntSushi/ripgrep#944] opened 2018-06-12 16:36 UTC
```
rg -e foo -v bar 
```
expected  result:
the line matching `foo` but not matching `bar`

**Comment by okdana** [comment] 2018-06-12 16:39
Duplicate of #875, #941, &c. See the second link for one work-around

**Closed** 2018-06-12 17:01 UTC
Labels: duplicate
