### ISSUE TITLE
Search lines matching two patterns or more

### ISSUE THREAD

**Issue by rik** [BurntSushi/ripgrep#473] opened 2017-05-04 14:25 UTC
`git grep` supports `--and` that allows you to match against all patterns instead of any pattern. Right now, I'm doing `rg pattern1|rg pattern2` but that gives a way less readable output than `rg --heading -e pattern1 --and -e pattern2` would.

**Comment by BurntSushi** [comment] 2017-05-04 14:36
It never ceases to amaze me how fundamentally opposed the Unix philosophy is to the nice colored output that tools like ack, ag and ripgrep use by default.

I reluctantly accept that this is desirable.

**Comment by BurntSushi** [comment] 2017-05-04 14:37
This ticket needs a more detailed specification before anyone should attempt to work on it. In particular, the interaction with other flags (like `--replace`, `-o`, etc.) needs to be ironed out.

**Comment by kpp** [comment] 2017-06-01 13:05
W8, what about `--or`? Are you going to give the user the power of the syntax of `find`?

**Comment by BurntSushi** [comment] 2017-06-01 13:16
@kpp What's wrong with `re1|re2`?

> Are you going to give the user the power of the syntax of find?

No. ripgrep is not a `find` replacement.

**Comment by BurntSushi** [comment] 2018-04-25 20:55
This is a duplicate of #875. Yeah, this ticket came first, but I've written more in #875, so I'm going to track this feature there.

**Closed by BurntSushi** 2018-04-25 20:55 UTC
Labels: enhancement, icebox, question
