### ISSUE TITLE
Different behaviors between rg, ag and grep

### ISSUE THREAD

**Issue by HongxuChen** [BurntSushi/ripgrep#959] opened 2018-06-22 07:09 UTC
This is not a big issue however I would like to make it clear.
For now `rg`'s behavior (also `ag`) is different from `grep` when matching text in binary files that contains a bunch of text: by default `rg`/`ag` will not match text when it determines that the file is a binary, but `grep` will still have a try.

As an example, for the file below:
[rg_grep_ag.txt](https://github.com/BurntSushi/ripgrep/files/2126627/rg_grep_ag.txt)
![2018-06-22-150654_1409x172_scrot](https://user-images.githubusercontent.com/843267/41762642-fb9aa46e-762d-11e8-8f72-670e953d8b4d.png)

**Comment by BurntSushi** [comment] 2018-06-22 10:48
Yes, ripgrep specifically skips binary files. This is part of its filtering logic.

Duplicate of #306 and/or #855.

**Closed by BurntSushi** 2018-06-22 10:48 UTC
