### ISSUE TITLE
Windows installation through command-line

### ISSUE THREAD

**Issue by Fireforge** [BurntSushi/ripgrep#386] opened 2017-02-28 18:49 UTC
You seem to have command line installation supported for every platform except Windows. Command-line installation on Windows is not yet common place, but it is out there:

- Scoop.sh: https://github.com/lukesampson/scoop
- Chocolatey: https://chocolatey.org/

Would you consider supporting one or both of these installation methods? The community (such as myself) could try to add them, but if you already officially support all the other platforms then hopefully it's not to hard to include these as well.

**Comment by BurntSushi** [comment] 2017-02-28 18:54
I don't personally support anything. (Well, I do have a brew tap associated with this repo, but that's temporary and for folks that want the SIMD accelerated version of ripgrep on Mac.)

I don't personally have any intention of fiddling with Windows package repositories. I just don't have the time to maintain that. It does however seem like ripgrep is already in Chocolatey according to #342.

Otherwise, I think this is a dupe of #10 and #342.

**Closed by BurntSushi** 2017-02-28 18:54 UTC

**Comment by Fireforge** [comment] 2017-02-28 19:06
Okay, I understand. It's all community support then I guess.

Thanks for the Chocolatey repo link (https://chocolatey.org/packages/ripgrep), it's up-to-date. I thought I had searched for ripgrep there, I don't know why that didn't show up. I could add that link to your Readme along with the others in a PR if you like.

**Comment by BurntSushi** [comment] 2017-02-28 19:10
> I could add that link to your Readme along with the others in a PR if you like.

That would be fantastic, thank you. :-) If it could include the basic install instructions like the others that'd be great too!
