### ISSUE TITLE
UTF16 BE support

### ISSUE THREAD

**Issue by martinlindhe** [BurntSushi/ripgrep#322] opened 2017-01-15 18:10 UTC
Hello. Am currently on Windows, and there for some reason (...) unicode files are often created as UTF16BE.
I realized I have a project with mixed file encodings, most is UTF8 and some are UTF16BE, and ripgrep currently don't find anything in those files.

In the attached archive is a project I was working on, and the file src\GUIGroup.ts happens to be in UTF16BE,
so try searching the folder for "GUIGroup" causes no hits in that file.

Tested with ripgrep 0.4.0 on Windows. Same result with ripgrep 0.4.0 on macOS

Github dont want to attach zip files today, so I put it here: 
http://wikisend.com/download/290136/utf16issue_ripgrep.zip

**Comment by BurntSushi** [comment] 2017-01-15 18:20
This is a dupe of #1.

As the README says, ripgrep doesn't seamlessly support any encoding that isn't ASCII compatible. (That includes UTF-8 and latin1, but not UTF-16.)

This is a desirable feature, especially at least UTF-16 since it is used a lot on Windows.

**Closed by BurntSushi** 2017-01-15 18:20 UTC

**Comment by martinlindhe** [comment] 2017-01-15 19:05
Ah, thanks. I glanced through the open issues looking for "UTF16", thats why I didn't notice #1.
