### ISSUE TITLE
Add sort option?

### ISSUE THREAD

**Issue by nerdrew** [BurntSushi/ripgrep#260] opened 2016-12-01 08:00 UTC
When using `rg` with `nvim` for my quickfix list, the results are no longer sorted. Thoughts on adding a sort option when sending output to a non-terminal? (It looks like the results do get sorted when it detects output is going to a terminal.)

**Comment by joeparkerz** [comment] 2016-12-01 08:02
This is a must for both input and output files. Please add!

Something like this is already done but not sure if it's still developed.
http://sgrep.sourceforge.net/

**Comment by BurntSushi** [comment] 2016-12-01 10:38
ripgrep has never done any sorting of any kind.

If you run ripgrep with `-j1`, then it will disable parallelism and should
result in deterministic output.

**Comment by BurntSushi** [comment] 2016-12-01 10:39
sgrep appears to be a completely different kind of search tool and also looks completely unrelated to this specific issue.

**Comment by BurntSushi** [comment] 2016-12-01 12:10
This appears to be a dupe of #263.

Notably, there's no regression here because ripgrep has *never* done sorting.

I don't know what ttys have to do with sorting. :-/ @nerdrew Perhaps you could clarify in #263.

**Closed by BurntSushi** 2016-12-01 12:10 UTC
