### ISSUE TITLE
grep's great --file option not implemented

### ISSUE THREAD

**Issue by seamusabshere** [BurntSushi/ripgrep#17] opened 2016-09-23 15:56 UTC
```
 -f file, --file=file
    Read one or more newline separated patterns from file.  Empty pattern
    lines match every input line.  Newlines are not considered part of a
    pattern.  If file is empty, nothing is matched.
```

🌞 note that neither `ag` or `ack` have this, so it would be another differentiator!

**Comment by BurntSushi** [comment] 2016-09-23 16:24
Dupe of #7.

And agreed. :-)

**Closed by BurntSushi** 2016-09-23 16:24 UTC
