### ISSUE TITLE
Using rg on a terminal prints loads of empty lines

### ISSUE THREAD

**Issue by dersebi** [BurntSushi/ripgrep#99] opened 2016-09-26 06:52 UTC
Using ripgrep on a Linux terminal prints loads of empty lines. I tried searching a big directory for a word without any additional options and there is pages of empty lines.
When redirecting the oputput to a file it does not include the empty lines.

I tested with a smaller directory and there are less empty lines.

As output redirection does not have a problem this might be related to special terminal characters?

My test system is an Ubuntu 14.04 LTS and I tested with uxterm and gnome-terminal.
I built ripgrep using cargo in release mode. My Rust version is 1.11.0.

**Comment by BurntSushi** [comment] 2016-09-26 09:42
Could you provide some input, preferably a single file, where this happens?
A screen shot or dump of the output would be helpful.

**Comment by dersebi** [comment] 2016-09-26 12:54
A simple test case would be the following:

    me@ubuntu:~ $ mkdir test
    me@ubuntu:~ $ cd test
    me@ubuntu:~/test $ echo "Hello World">test1
    me@ubuntu:~/test $ rg World
    test1
    1:Hello World
    me@ubuntu:~/test $ touch test2
    me@ubuntu:~/test $ rg World
    test1
    1:Hello World
    
    me@ubuntu:~/test $
    me@ubuntu:~/test $ touch test3
    me@ubuntu:~/test $ rg World
    test1
    1:Hello World
    
    
    me@ubuntu:~/test $

I haven't verified this, but is seems to add an empty line for each file without a match.

**Comment by BurntSushi** [comment] 2016-09-26 13:07
Weird, I can't reproduce:

```
[andrew@Serval 99] l
total 0
[andrew@Serval 99] echo "Hello World" > test1
[andrew@Serval 99] rg World
test1
1:Hello World
[andrew@Serval 99] touch test2
[andrew@Serval 99] rg World
test1
1:Hello World
[andrew@Serval 99] touch test3
[andrew@Serval 99] rg World
test1
1:Hello World
```

Could you try your test case again with `--color=never`? Also, what is the output of `echo $TERM`?

**Comment by dersebi** [comment] 2016-09-26 13:51
`--color=never` yields the same result with the empty lines, except that it is not colored (obviously)
`TERM` is set to `xterm`

**Comment by BurntSushi** [comment] 2016-09-26 20:57
Hmm, I'm not sure what's causing this and I can't reproduce it. :-/

Probably my next step is firing up an Ubuntu 14.04 VM, and it may take me a while to get to that.

**Comment by windware** [comment] 2016-09-26 23:12
I can reproduce this on Ubuntu 16.04 64bit

**Comment by BurntSushi** [comment] 2016-09-26 23:34
@windware AH! Dammit. This is another single threaded bug. I really wish I could DRY that up. Thank you so much for looking into this because you just saved me a bunch of time!

(P.S. Try running `rg -j1 ...` on Centos and it should repro.)

**Comment by windware** [comment] 2016-09-26 23:40
-j1 did it on CentOS but it only produced a single blank line with my above example.
-j2 also made a single blank line but -j3 and -j4 removed it.

**Comment by BurntSushi** [comment] 2016-09-26 23:57
OK, this should be fixed. This was a regression I introduced last night. :-(

**Closed** 2016-09-26 23:57 UTC
Labels: question

**Comment by dersebi** [comment] 2016-09-27 06:33
Fixed indeed. Much better, thanks!
