### ISSUE TITLE
Is it possible to provide the files to be searched in a file rather than on the command line?

### ISSUE THREAD

**Issue by jborgh** [BurntSushi/ripgrep#1525] opened 2020-03-19 16:55 UTC
#### What version of ripgrep are you using?
ripgrep 11.0.2 (rev 3de31f7527)

#### How did you install ripgrep?
scoop 

#### What operating system are you using ripgrep on?
Windows 10

#### Describe your question, feature request, or bug.
I am interested in searching a specific set of files which I am currently specifying on the command line as the `[PATH ...]` argument. I'm wondering if there is something similar to the `--file` flag (which is for patterns) to specify a file containing a list of file paths to search instead?

Currently, I sometimes have to invoke `rg` multiple times since I'm hitting the max command line length.

**Comment by BurntSushi** [comment] 2020-03-19 16:59
Duplicate of #273.

**Closed by BurntSushi** 2020-03-19 16:59 UTC
Labels: duplicate

**Comment by jborgh** [comment] 2020-03-19 17:09
Thanks for the quick reponse!

**Comment by habamax** [comment] 2020-05-25 09:24
@jborgh how did you resolve the issue?
