### ISSUE TITLE
search summary at the end

### ISSUE THREAD

**Issue by sjLambda** [BurntSushi/ripgrep#605] opened 2017-09-16 17:15 UTC
How can I get a summary of the search at the end? 

For example, ag gives this:

264 matches
48 files contained matches
307 files searched
16778135 bytes searched
3.377348 seconds

Is there a way to get some or all such stats with rg?

**Comment by BurntSushi** [comment] 2017-09-16 17:18
dupe of #411 

(To answer your question, no, ripgrep doesn't have this. Use `rg foo | wc -l` or `rg -l foo | wc -l` or `rg -c foo` for now.)

**Comment by sjLambda** [comment] 2017-09-17 07:54
Then I get the stats and not the search hits.

**Comment by BurntSushi** [comment] 2017-09-17 12:23
@sjLambda It's a work around. That's why there's an issue open for it. Did you read it?

Anyway, this is clearly a duplicate, so I'm closing.

**Closed by BurntSushi** 2017-09-17 12:23 UTC
Labels: duplicate
