### ISSUE TITLE
Tiny bug in document for `-P, --pcre2` option

### ISSUE THREAD

**Issue by zufuliu** [BurntSushi/ripgrep#1551] opened 2020-04-13 06:39 UTC
https://github.com/BurntSushi/ripgrep/blob/master/crates/core/app.rs#L2377

in `fn flag_pcre2(args: &mut Vec<RGArg>)`, I think `\n` is `\\n`. 
the output for `rg --help` now shows:
```
...
some cases, since it has fewer introspection APIs than ripgrep's default regex
engine. For example, if you use a '
' in a PCRE2 regex without the
'-U/--multiline' flag, then ripgrep will silently fail to match anything
...
```

**Comment by BurntSushi** [comment] 2020-04-13 12:26
Could you please provide more details? There is an issue template. Please fill it out.

In particular, I cannot reproduce this problem:
![rgman](https://user-images.githubusercontent.com/456674/79120232-6f8c0080-7d60-11ea-9f1e-ff689a199834.png)

**Comment by zufuliu** [comment] 2020-04-13 12:31
https://github.com/BurntSushi/ripgrep/releases/download/12.0.1/ripgrep-12.0.1-x86_64-pc-windows-msvc.zip
```
rg --version
ripgrep 12.0.1 (rev 1d5b1011e5)
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)
```

on Win10 1909 x64 Windows Command Prompt.
![rg-help](https://user-images.githubusercontent.com/2289926/79120557-be1fb600-7dc5-11ea-86dc-f1b2ee8fc249.png)

**Comment by BurntSushi** [comment] 2020-04-13 12:35
What command are you running to render the man page? Is it `man`? If so, what version of `man`?

**Comment by zufuliu** [comment] 2020-04-13 12:35
look at your own screenshot, I think it should be `\n` but is empty inside single quotes.
> For example, if you use a ' '  in a PCRE2 regex without the

**Comment by zufuliu** [comment] 2020-04-13 12:36
the `rg --help` command on cmd.exe (Windows Command Prompt).

**Comment by zufuliu** [comment] 2020-04-13 12:40
Same result when running in MSYS2's mintty (MINGW64)
![rg-help-mintty](https://user-images.githubusercontent.com/2289926/79121006-dcd27c80-7dc6-11ea-8d53-b568e9d739be.png)

**Comment by BurntSushi** [comment] 2020-04-13 12:50
Ah great, thanks. For some reason I thought you were looking at the man page. This is now fixed on master.

**Closed** 2020-04-13 12:50 UTC
Labels: question
