### ISSUE TITLE
Automatically switch to case-insensitive mode if the query is all lowercase

### ISSUE THREAD

**Issue by alex** [BurntSushi/ripgrep#424] opened 2017-03-30 00:31 UTC
This is a great feature that `ag` has. If your search is all lowercase, it'll switch to `-i` automatically, which it turns out is basically always what I want :-)

(PS: `rg` is fantastic, thank you!)

**Comment by BurntSushi** [comment] 2017-03-30 00:36
This is a dupe of #70. The short story is that the `-S/--smart-case` flag already exists, so all you need to do is `alias rg="rg --smart-case"` in your `.bashrc` and you should be good to go.

I'm strongly opposed to making this the default.

> (PS: rg is fantastic, thank you!)

:-)

**Closed by BurntSushi** 2017-03-30 00:36 UTC

**Comment by alex** [comment] 2017-03-30 00:37
Doh, sorry about the dupe. Thanks!
