### ISSUE TITLE
Excluded directories in .gitignore are ignored

### ISSUE THREAD

**Issue by codido** [BurntSushi/ripgrep#759] opened 2018-01-25 11:23 UTC
If a directory matches a pattern in .gitignore but then explicitly excluded (with '!'), its contents is still ignored by ripgrep.

**Comment by BurntSushi** [comment] 2018-01-25 11:37
@codido This bug report contains insufficient detail to be actionable. Please provide a small reproducible example. Please show all inputs, actual output and expected output.

**Comment by codido** [comment] 2018-01-25 11:53
The following demonstrates the issue:
```
mkdir -p test/foo
echo foobar > test/foo/bar
echo 'f*' > test/.gitignore
echo '!foo' >> test/.gitignore
rg foo
```

Expected output:
```
test/foo/bar
1:foobar
```

Actual output:
```
No files were searched, which means ripgrep probably applied a filter you didn't expect. Try running again with --debug.
```

**Comment by BurntSushi** [comment] 2018-01-25 12:01
This is basically a different variation of this recently reported issue: https://github.com/BurntSushi/ripgrep/issues/755

The problem is that `f*` will trip on paths like `./test/foo/bar` (globs without an explicit `/` in them will permit `*` to match `/`, as per `man gitignore` semantics). In particular, your `!foo` whitelist rule works in the sense that `./test/foo` is whitelisted (you can see confirmation of this by running ripgrep with `--debug`, as indicated in the error message you got). But whitelisting `./test/foo` does not mean that `./test/foo/bar` is whitelisted.

You can fix this is one of two ways. In addition to the `!foo` pattern, add `!**/foo/**` (or `!/foo/**` as appropriate). This will cause your `test/foo/bar` file to get whitelisted. The other way to fix this is to make your initial ignore rule more specific. That is, use `**/f*` instead of `f*`.

**Comment by codido** [comment] 2018-01-25 12:12
@BurntSushi Thanks for elaborating on that (and of course for ripgrep :)).

While I can fix this in my own trees (if I ever do this), I actually ran into this in an external project. It should be noted that git is OK with these (that is, it doesn't ignore foo/bar), as well as ag, so shouldn't ripgrep behave the same?

**Comment by BurntSushi** [comment] 2018-01-25 12:21
ag should never ever be used as the gold standard for gitignore rules. If it gets this case right, it's by accident.

In order for ripgrep to "behave the same," we need a specification of what `git` is actually doing. gitignore handling is *incredibly* complex, and just inventing new rules on the fly is unlikely to work well. In ripgrep's case, we try to match the specification written in `man gitignore` precisely. If someone can manage to tweak that specification in a rigorous way that fixes a case like yours, then I might be open to exploring it further. There's no obvious tweak that comes to mind for this case, other than something like, "a higher precedent whitelist rule on a parent directory overrides a lower precedent rule on a file in that directory." But that's trivially wrong. e.g., if you had `*.log` as a gitignore rule but `foo` as a whitelist rule, then you'd still expect `foo/wat.log` to be ignored. So there is something deeper going on here that needs to be figured out before we can fix this.

Note that ripgrep can never be 100% in sync with git. For example, if you have a file that is ignored but is nevertheless committed, then git will stick track it but ripgrep will still ignore it.

In the abstract, I agree that in an ideal world, the files known to git are exactly the same as the files searched by ripgrep.

**Comment by codido** [comment] 2018-01-25 12:40
@BurntSushi Sure thing, thanks again.

**Comment by BurntSushi** [comment] 2018-01-31 02:06
Based on my previous comment, I'm going to close this. I'm open to alternative ideas here, but they likely need to be well researched.

**Closed by BurntSushi** 2018-01-31 02:06 UTC
Labels: question
