### ISSUE TITLE
grep with multiple AND patterns

### ISSUE THREAD

**Issue by moroal** [BurntSushi/ripgrep#1217] opened 2019-03-11 01:12 UTC
#### What version of ripgrep are you using?
0.10.0

#### How did you install ripgrep?
unzip binary releases

#### What operating system are you using ripgrep on?
win7

#### Describe your question, feature request, or bug.
feature request：grep with multiple AND patterns
such as :  rg word1&word2&word3
not : rg word1 | rg word2 | rg word3
because the second one prints the file path as a prefix for each matched line instead of printing the file path above clusters of matches from each file

**Comment by BurntSushi** [comment] 2019-03-11 01:20
Dupe of https://github.com/BurntSushi/ripgrep/issues/875

My feeling is that this is unlikely to happen. You'll just have to deal with the traditional output format.

**Closed by BurntSushi** 2019-03-11 01:20 UTC

**Comment by moroal** [comment] 2019-03-12 01:28
Thanks for your reply.

Is there any way to print the file path above clusters of matches from each file and to color each keyword?

> rg word1 | rg word2 | rg word3

expect：
file1
xxxx word1 word2 word3 xxxx
xxxxxxx word1 xxxxxxx  word2  xxxx word3 
file2
xxxx word1 word2 word3 xxxx
xxxxxxx word1 xxxxxxx  word2  xxxx word3 

not

file1:xxxx word1 word2 word3 xxxx
file1:xxxxxxx word1 xxxxxxx  word2  xxxx word3 
file2:xxxx word1 word2 word3 xxxx
file2:xxxxxxx word1 xxxxxxx  word2  xxxx word3 

May I have some suggestions on how to use it? Thank you.

**Comment by BurntSushi** [comment] 2019-03-12 02:12
No, not unless you're okay with an OR instead of an AND. Otherwise, this is the key downside of using a format that isn't line oriented. Namely, it is not composable.

**Comment by moroal** [comment] 2019-03-13 11:47
Okay, but I'm still a ripgrep fan.
