### ISSUE TITLE
Exclude Directories Not Working

### ISSUE THREAD

**Issue by mattmccormick** [BurntSushi/ripgrep#2165] opened 2022-03-18 18:12 UTC
Hi there,

I'm trying to exclude directories from my search.  I'm using the following command:

```shell
rg --fixed-strings --max-filesize 50K --max-count 1 --glob '![/sys/devices/*, /proc/*]' --files espanso /
```

But in the output I clearly see files that match directories starting with `/proc`.  What am I doing wrong?  I've also tried a bunch of other things like using double stars.

I'm using version 11.0.2

**Comment by BurntSushi** [comment] 2022-03-18 18:17
This looks like a duplicate of #2156.

**Comment by BurntSushi** [comment] 2022-03-18 18:18
(Also, I don't know where the `[x, y]` glob syntax came from. That's not standard at all and is certainly not supported by ripgrep.)

**Closed** 2022-03-18 18:17 UTC
Labels: duplicate
