### ISSUE TITLE
ignore rules relativized to command line path

### ISSUE THREAD

**Issue by mobileink** [BurntSushi/ripgrep#1778] opened 2021-01-07 14:09 UTC
#### What version of ripgrep are you using?

ripgrep 12.1.0
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)

#### How did you install ripgrep?

I don't remember

#### What operating system are you using ripgrep on?

MacOS 10.15.7

#### Describe your bug.

I need to ignore `src/lib/snarky/website`.  If I add this to  `.ignore` and run `rg foo src/` it has no effect. However, if I add `lib/snarky/website` to `src/.ignore` then it is ignored.  

Furthermore `rg foo src/lib` fails (does not ignore) with both `src/.ignore`and `.ignore` but succeeds with `src/lib/.ignore`

Whether or not this is a bug is debatable, but it is surprising and cumbersome, since it requires that I match my .ignore files to my search command. Sometimes I want to search `src/` and sometimes `src/lib`, so I have to sprinkle `.ignore` files throughout my source tree.

**Comment by BurntSushi** [comment] 2021-01-07 14:25
Dupe of #829.

**Closed** 2021-01-07 14:25 UTC
Labels: duplicate
