### ISSUE TITLE
Support for multi-line match

### ISSUE THREAD

**Issue by kenorb** [BurntSushi/ripgrep#886] opened 2018-04-15 00:48 UTC
#### What version of ripgrep are you using?

`ripgrep 0.8.1`

#### What operating system are you using ripgrep on?

macOS High Sierra

#### Feature

I am running the following command:

    printf "foo\r\nbar\r\n" | rg "(?ms)foo.*bar"

and I would expect the match given the [multi-line mode](https://github.com/robinst/regex/blob/master/src/lib.rs#L341).

**Comment by BurntSushi** [comment] 2018-04-15 00:50
@kenorb Filing a flurry of issues without searching the issue tracker isn't appreciated. 

Dupe of #176.

**Closed by BurntSushi** 2018-04-15 00:50 UTC
