### ISSUE TITLE
Input ignored when Windows command pipes output to ripgrep

### ISSUE THREAD

**Issue by Praful** [BurntSushi/ripgrep#160] opened 2016-10-10 02:13 UTC
When you pipe output of a Windows command to `rg`, `rg `ignores it and searches folders.

For example, the output of `dir ` is ignored by `rg ` in:

```
dir /s |rg -i test
```

If `rg ` is replaced by `findstr`, `ack ` or `pt`, the correct output is displayed.

I have tried this only on Windows 10.

**Comment by BurntSushi** [comment] 2016-10-10 16:25
This is a duplicate of #94.

For a work-around, use `dir /s | rg -i test -`.

**Closed by BurntSushi** 2016-10-10 16:25 UTC
