### ISSUE TITLE
replacements - $1 not recognized if followed by underscore

### ISSUE THREAD

**Issue by brunetton** [BurntSushi/ripgrep#2455] opened 2023-03-15 00:18 UTC
#### What version of ripgrep are you using?

ripgrep 13.0.0

#### How did you install ripgrep?

Debian

#### What operating system are you using ripgrep on?

Ubuntu 22.04

#### Describe your bug.

Can't use `$1` in replacements when followed by underscore

#### What are the steps to reproduce the behavior?

`echo "hello" | rg '(.*)' -r '--$1_--'`

#### What is the actual behavior?

```
DEBUG|rg::config|crates/core/config.rs:40: /home/bruno/.ripgreprc: arguments loaded from config file: ["--no-line-number"]
DEBUG|rg::args|crates/core/args.rs:543: final argv: ["rg", "--no-line-number", "(.*)", "-r", "--$1_--", "--debug"]
DEBUG|globset|/usr/share/cargo/registry/ripgrep-13.0.0/debian/cargo_registry/globset-0.4.8/src/lib.rs:421: built glob set; 0 literals, 0 basenames, 12 extensions, 0 prefixes, 0 suffixes, 0 required extensions, 0 regexes
----
```

#### What is the expected behavior?

Output should be: `--hello_--`

**Comment by BurntSushi** [comment] 2023-03-15 00:48
Duplicate of #2201.

Use `${1}` instead. Otherwise the `_` is treated as part of the capture group reference.

**Closed** 2023-03-15 00:48 UTC
