### ISSUE TITLE
searching for a list of entries in a specific directory

### ISSUE THREAD

**Issue by DanielsBerlin** [BurntSushi/ripgrep#2385] opened 2022-12-31 07:08 UTC
hi, and thanks for the program.
suppose that i have a list which contains 100 entries, and i have a directory that contains some txt files and some zip files. so i want to search the list inside that directory in a way that when any of the entries are hit in that directory , the program needs to list those matching entries.
how to write a command for this

**Comment by BurntSushi** [comment] 2022-12-31 11:46
Duplicate of #2383.

**Closed by BurntSushi** 2022-12-31 11:46 UTC
