### ISSUE TITLE
"file length overflows usize"

### ISSUE THREAD

**Issue by K-arti-k** [BurntSushi/ripgrep#922] opened 2018-05-19 19:35 UTC
**#### What version of ripgrep are you using?**

`ripgrep 0.7.1
-AVX -SIMD`.

**#### What operating system are you using ripgrep on?**

Operating System: 64-bit
Windows 7: Cygwin Terminal

**#### Describe your question, feature request, or bug.**

With specific files when trying to grep I get an error saying "file length overflows usize"

**#### If this is a bug, what are the steps to reproduce the behavior?**

$ ./rg -i -w "Gurkiran" "zoosk.txt"
file length overflows usize

**Comment by BurntSushi** [comment] 2018-05-19 21:03
Sorry, but this isn't reproducible. Please provide enough information (like the file you're searching) in order to reproduce the problem.

**Comment by peter-bertok** [comment] 2018-07-05 06:20
This is indirectly caused by this issue in memmap-rs: https://github.com/danburkert/memmap-rs/issues/67

Someone already submitted a patch for memmap-rs back in April 2018, but fixing this for the general case will take some time...

**Comment by danburkert** [comment] 2018-07-05 16:46
Something doesn't add up here.  Ripgrep isn't using file offsets, so the usize/u64 offset API issue in memmap shouldn't be in play here.  That error message only occurs when you attempt to memory map a file whose length exceeds `usize::MAX`.  That shouldn't be possible on a 64-bit OS.

**Comment by BurntSushi** [comment] 2018-07-05 16:58
@danburkert Yeah, something is definitely fishy with thia bug report. Either the info is probably wrong, or Windows is running in 32 bit mode or maybe even they downloaded the 32 bit executable? I don't know.

**Comment by BatmanAoD** [comment] 2018-07-05 21:37
Per @peter-bertok's [comment in users.rust-lang](https://users.rust-lang.org/t/rust-beginner-notes-questions/14928/78?u=batmanaod), this is indeed reproducible with the 32 bit executable, so I expect @K-arti-k did indeed encounter this issue with the 32 bit executable.

I feel that searching through a multi-Gb file in 32-bit mode is not a particularly compelling use-case for RipGrep. That said, Peter Bertok is presumably correct that this could eventually be fixed in a future version of `memmap-rs`.

**Comment by BurntSushi** [comment] 2018-07-05 21:54
@BatmanAoD Note that this bug should be fixed on master. ripgrep just won't use memory maps and use standard read calls instead.

**Comment by danburkert** [comment] 2018-07-05 22:07
> That said, Peter Bertok is presumably correct that this could eventually be fixed in a future version of memmap-rs.

No, this is not correct.  This ripgrep issue has no relation to the u64/usize offset API issue, which is the only `memmap` bug which has been brought forward.  It's fundamentally not possible to create a memory map with a length which exceeds `usize::MAX`.

**Comment by BatmanAoD** [comment] 2018-07-05 22:18
@danburkert In the linked discussion (which unfortunately is long and contentious, and has a broad range of topics that are mostly unrelated), [@peter-bertok claims](https://users.rust-lang.org/t/rust-beginner-notes-questions/14928/83?u=batmanaod) that 32-bit systems *can* create memory maps for *arbitrarily* sized files, using "views" that fit into the actual available memory space (which is really `isize::MAX` rather than `usize::MAX` for some or possibly all 32-bit Windows OSes).

**Closed** 2018-08-20 11:10 UTC
Labels: libripgrep, question
