### ISSUE TITLE
Replacing a multiline expression duplicates non-matched lines

### ISSUE THREAD

**Issue by miquella** [BurntSushi/ripgrep#2303] opened 2022-09-12 23:19 UTC
#### What version of ripgrep are you using?

```
ripgrep 13.0.0
-SIMD -AVX (compiled)
```

#### How did you install ripgrep?

```
brew install ripgrep
```

#### What operating system are you using ripgrep on?

macOS v12.5.1

#### Describe your bug.

Replacing a multiline string duplicates the following non-matched line.

#### What are the steps to reproduce the behavior?

Using the following corpus:

```console
$ printf 'A\nB\nC\nD\n'
A
B
C
D
```

The following `rg` commands seem to duplicate one of the lines (`D`):

```console
$ printf 'A\nB\nC\nD\n' | rg -U "B\nC" --replace "r"
```

```console
$ printf 'A\nB\nC\nD\n' | rg -U "B\nC" --replace "r" --passthru
```

#### What is the actual behavior?

```console
$ printf 'A\nB\nC\nD\n' | rg -U "B\nC" --replace "r" --passthru --debug
DEBUG|globset|crates/globset/src/lib.rs:421: built glob set; 0 literals, 0 basenames, 12 extensions, 0 prefixes, 0 suffixes, 0 required extensions, 0 regexes
DEBUG|globset|crates/globset/src/lib.rs:421: built glob set; 0 literals, 2 basenames, 0 extensions, 0 prefixes, 0 suffixes, 0 required extensions, 0 regexes
A
r
D
D
```

#### What is the expected behavior?

```console
$ printf 'A\nB\nC\nD\n' | rg -U "B\nC" --replace "r" --passthru
A
r
D
```

**Comment by BurntSushi** [comment] 2022-09-13 00:19
Dupe of #2095.

Confirmed that this is fixed on current master:

```
$ printf 'A\nB\nC\nD\n' | rg-13.0.0 -U "B\nC" --replace "r" --passthru
A
r
D
D
$ printf 'A\nB\nC\nD\n' | rg -U "B\nC" --replace "r" --passthru
A
r
D
```

**Closed by BurntSushi** 2022-09-13 00:19 UTC

**Comment by miquella** [comment] 2022-09-13 05:08
@BurntSushi: Awesome, thanks!
