### ISSUE TITLE
searching plaintext files inside zip archives

### ISSUE THREAD

**Issue by eadmaster** [BurntSushi/ripgrep#1479] opened 2020-02-07 20:46 UTC
#### What version of ripgrep are you using?

ripgrep 11.0.2
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)

#### How did you install ripgrep?

https://github.com/BurntSushi/ripgrep/releases/download/11.0.2/ripgrep-11.0.2-x86_64-unknown-linux-musl.tar.gz

#### What operating system are you using ripgrep on?

  Operating System: Ubuntu 18.04.2 LTS
            Kernel: Linux 4.15.0-50-generic
      Architecture: x86-64

#### If this is a bug, what are the steps to reproduce the behavior?

`rg --search-zip "Super Metroid"  "$PENDRIVE/Documents/db/datfile/No Intro DAT-o-MATIC (2016-01-03).zip"`

#### If this is a bug, what is the actual behavior?

(no output)

#### If this is a bug, what is the expected behavior?

Should look for matches inside the zip archive

**Comment by BurntSushi** [comment] 2020-02-07 23:48
Duplicate of https://github.com/BurntSushi/ripgrep/issues/1112

**Closed by BurntSushi** 2020-02-07 23:48 UTC
Labels: duplicate
