### ISSUE TITLE
Suggest: change the directory separate char '\\' to '/' on windows

### ISSUE THREAD

**Issue by cn00** [BurntSushi/ripgrep#721] opened 2017-12-29 10:13 UTC
The windows directory separate char '\\'  always case some problems, maybe use the Unix directory separate char '/' is more convenient.
I love ripgrep, thanks for your jobs.

**Comment by BurntSushi** [comment] 2017-12-29 10:34
This is a duplicate. Please search issue tracker.

**Comment by BurntSushi** [comment] 2017-12-29 11:44
I was on mobile before. This is a dupe of #711. Use the `--path-separator` flag to get what you want.

**Closed by BurntSushi** 2017-12-29 11:44 UTC
