### ISSUE TITLE
Provide ability to provide "function" context

### ISSUE THREAD

**Issue by Mark-Simulacrum** [BurntSushi/ripgrep#282] opened 2016-12-18 15:57 UTC
It would be convenient to be able to specify an option to print matches with not only file and line number information, but also the nearest function definition. This can be expanded to nearest (going from top to bottom) match of a regex for extra flexibility.

**Comment by BurntSushi** [comment] 2016-12-18 16:01
This would be cool, but I think it's a dupe of #236. The TL;DR is that ripgrep is a line oriented search tool. This feature fundamentally violates that. (This isn't just a philosophical objection either, line oriented search tools and language/context aware search tools are different beasts through-and-through.)

**Closed by BurntSushi** 2016-12-18 16:01 UTC

**Comment by Mark-Simulacrum** [comment] 2016-12-18 19:04
Yeah, I see how that's true. This might be better in another issue, but what about a more general line-based solution that allows you to specify an "or" effectively; e.g. `rg '\.call' --or 'fn ' ` would print both all lines matching `\.call` and `fn ` interleaved, giving effectively what I originally wanted (though, admittedly, with extra noise).

The reason why I think this sort of is still a good fit for ripgrep despite it being line oriented is that it doesn't really violate it: all I want is a way to "remember" a single line (or just --or, as I said above).

**Comment by BurntSushi** [comment] 2016-12-18 19:17
You should be able to do that today using either a normal `|` in a single regex, or you can use the `-e/--regexp` flag to specify multiple regexes at once (just like grep allows). Does that help?

**Comment by Mark-Simulacrum** [comment] 2016-12-18 23:29
Ah, I didn't know I could specify multiple `-e` options. Thanks!

**Comment by BurntSushi** [comment] 2016-12-19 01:37
Fwiw, the implementation of multiple -e flags is just a simple application of |.
