### ISSUE TITLE
max-columns-preview surrounding context for first match

### ISSUE THREAD

**Issue by fallalex** [BurntSushi/ripgrep#1649] opened 2020-07-30 20:42 UTC
It would be helpful to see the surrounding context of a match buried in a long line rather than just seeing the beginning of the line. Not wanting to replace the max-columns-preview functionality but maybe add another flag to change the preview mode from start of line to the surrounding context (split between before and after the match).

**Comment by BurntSushi** [comment] 2020-07-30 23:47
Dupe of #1352

**Closed by BurntSushi** 2020-07-30 23:47 UTC
