### ISSUE TITLE
--color never not supported for error output

### ISSUE THREAD

**Issue by andreastt** [BurntSushi/ripgrep#353] opened 2017-02-09 13:44 UTC
My shell does not support colours and consequently I set the environmental variable `TERM=dumb` to instruct programs never to colourise output.

However, even when I pass `--color never` to rg, the error output includes colour escape codes as can be seen below:

```
% rg --color never -asd
[1;31merror:[0m Found argument '[33m-d[0m' which wasn't expected, or isn't valid in this context

USAGE:
    
    rg [OPTIONS] <pattern> [<path> ...]
    rg [OPTIONS] [-e PATTERN | -f FILE ]... [<path> ...]
    rg [OPTIONS] --files [<path> ...]
    rg [OPTIONS] --type-list

For more information try [32m--help[0m
```

**Comment by kbknapp** [comment] 2017-02-09 16:44
@andreastt that's from [`clap`](https://github.com/kbknapp/clap-rs)s (`rg`'s CLI parser) error message, not `rg`'s.

I think there's a hacky way to workaround this...but it's hacky. You'd essentially be parsing the CLI twice in the case of a `CLI` error and then double checking that `--color never`. An abbriviated version is something like:

```rust
let mut app = build_cli();
let args: Args = match app.get_matches_safe() {
    Err(e) => {
        if env::args().find(|arg| arg == "--color").is_some() && env::arg().find(|arg| arg == "never") {
            app.setting(AppSettings::ColorNever).get_matches();
        } 
        e.exit();
    },
    Ok(m) => m.into(),
};
```

There's probably a *far* better way to do all that, but I'm going a lack of sleep and 8 plane rides 😜

**Comment by BurntSushi** [comment] 2017-02-09 16:49
@kbknapp Yeah, probably the "right" way here is for clap to recognize `TERM=dumb`, which should mean "no colors." (It's pretty standard in my experience, and [`termcolor`](https://github.com/BurntSushi/ripgrep/blob/master/termcolor/src/lib.rs#L116) will Do The Right Thing.)

**Comment by kbknapp** [comment] 2017-02-09 16:49
@andreastt if you wouldn't mind, could you file an issue in `clap`s repo too? This is something that I'd like to at least attempt to address on that side of things.

**Comment by kbknapp** [comment] 2017-02-09 16:50
@BurntSushi yep, once I get some time to sit down and actually implement kbknapp/clap-rs#836 that's my exact plan :wink:

**Comment by BurntSushi** [comment] 2017-02-09 16:51
@kbknapp While you're at it, note that the [`atty`](https://github.com/softprops/atty) crate now supports MSYS terminals and native Windows consoles. I've wondered whether `termcolor` itself should use the `atty` crate directly.

**Comment by andreastt** [comment] 2017-02-09 16:55
Filed https://github.com/kbknapp/clap-rs/issues/847 with clap.

**Comment by BurntSushi** [comment] 2017-05-08 22:02
If someone wants to fix this using [@kbknapp's hack](https://github.com/BurntSushi/ripgrep/issues/353#issuecomment-278699290), then I'd be open to it. It might be hard to write a regression test for it though.

**Comment by nateozem** [comment] 2017-05-13 23:37
Sure, I'll take a stab at it.

**Comment by nateozem** [comment] 2017-05-17 10:13
There's a PR for `clap-rs` to comply with terminfo when `TERM=dumb`  (https://github.com/kbknapp/clap-rs/pull/963). 
Anything else needs to be done? Still prefer to be colorless if `--color never`?

**Comment by BurntSushi** [comment] 2017-05-17 11:01
@nateozem Let's try to get away with `TERM=dumb` support instead of introducing a hack.

**Comment by BurntSushi** [comment] 2017-10-22 01:54
It looks like the clap PR was merged so I'm marking this as fixed. (You still can't use `--color never`, but `TERM=dumb` should be respected.)

**Closed by BurntSushi** 2017-10-22 01:54 UTC
Labels: bug, help wanted
